# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPasswordDialog(object):
    def setupUi(self, addPasswordDialog):
        addPasswordDialog.setObjectName("addPasswordDialog")
        addPasswordDialog.setEnabled(True)
        addPasswordDialog.resize(400, 110)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addPasswordDialog.sizePolicy().hasHeightForWidth())
        addPasswordDialog.setSizePolicy(sizePolicy)
        addPasswordDialog.setMinimumSize(QtCore.QSize(400, 80))
        addPasswordDialog.setMaximumSize(QtCore.QSize(400, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        addPasswordDialog.setFont(font)
        addPasswordDialog.setSizeGripEnabled(False)
        addPasswordDialog.setModal(False)
        self.layoutWidget = QtWidgets.QWidget(addPasswordDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 382, 88))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMaximumSize(QtCore.QSize(180, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setMaxLength(12)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout.addWidget(self.lineEditPassword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.lineEditConfirmPassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditConfirmPassword.setMaximumSize(QtCore.QSize(180, 24))
        self.lineEditConfirmPassword.setMaxLength(12)
        self.lineEditConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditConfirmPassword.setObjectName("lineEditConfirmPassword")
        self.horizontalLayout_9.addWidget(self.lineEditConfirmPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(380, 30))
        self.buttonBox.setMaximumSize(QtCore.QSize(380, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("        QPushButton {\n"
"        font: 9pt \"Calibri\";\n"
"        width: 120px;\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 5 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addPasswordDialog)
        self.buttonBox.accepted.connect(addPasswordDialog.accept)
        self.buttonBox.rejected.connect(addPasswordDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addPasswordDialog)

    def retranslateUi(self, addPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        addPasswordDialog.setWindowTitle(_translate("addPasswordDialog", "Dialog"))
        self.label_1.setText(_translate("addPasswordDialog", "Please enter your password"))
        self.label.setText(_translate("addPasswordDialog", "Please confirm your password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addPasswordDialog = QtWidgets.QDialog()
    ui = Ui_addPasswordDialog()
    ui.setupUi(addPasswordDialog)
    addPasswordDialog.show()
    sys.exit(app.exec_())
