# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'co_socket_type_and_num_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_co_socket_type_and_num_select(object):
    def setupUi(self, co_socket_type_and_num_select):
        co_socket_type_and_num_select.setObjectName("co_socket_type_and_num_select")
        co_socket_type_and_num_select.setEnabled(True)
        co_socket_type_and_num_select.resize(425, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(co_socket_type_and_num_select.sizePolicy().hasHeightForWidth())
        co_socket_type_and_num_select.setSizePolicy(sizePolicy)
        co_socket_type_and_num_select.setMinimumSize(QtCore.QSize(425, 130))
        co_socket_type_and_num_select.setMaximumSize(QtCore.QSize(425, 130))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        co_socket_type_and_num_select.setFont(font)
        co_socket_type_and_num_select.setSizeGripEnabled(False)
        co_socket_type_and_num_select.setModal(False)
        self.layoutWidget = QtWidgets.QWidget(co_socket_type_and_num_select)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 404, 117))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.socket_type_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.socket_type_label.setFont(font)
        self.socket_type_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.socket_type_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.socket_type_label.setTextFormat(QtCore.Qt.AutoText)
        self.socket_type_label.setScaledContents(False)
        self.socket_type_label.setWordWrap(False)
        self.socket_type_label.setObjectName("socket_type_label")
        self.horizontalLayout.addWidget(self.socket_type_label)
        self.socket_type_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.socket_type_comboBox.setFont(font)
        self.socket_type_comboBox.setStyleSheet("QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.socket_type_comboBox.setObjectName("socket_type_comboBox")
        self.horizontalLayout.addWidget(self.socket_type_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.socket_num_label = QtWidgets.QLabel(self.layoutWidget)
        self.socket_num_label.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.socket_num_label.setFont(font)
        self.socket_num_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.socket_num_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.socket_num_label.setTextFormat(QtCore.Qt.AutoText)
        self.socket_num_label.setScaledContents(False)
        self.socket_num_label.setWordWrap(False)
        self.socket_num_label.setObjectName("socket_num_label")
        self.horizontalLayout_2.addWidget(self.socket_num_label)
        self.socket_num_reduce = QtWidgets.QPushButton(self.layoutWidget)
        self.socket_num_reduce.setObjectName("socket_num_reduce")
        self.horizontalLayout_2.addWidget(self.socket_num_reduce)
        self.socket_num_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.socket_num_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.socket_num_edit.setReadOnly(False)
        self.socket_num_edit.setObjectName("socket_num_edit")
        self.horizontalLayout_2.addWidget(self.socket_num_edit)
        self.channel_number_add = QtWidgets.QPushButton(self.layoutWidget)
        self.channel_number_add.setObjectName("channel_number_add")
        self.horizontalLayout_2.addWidget(self.channel_number_add)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(400, 30))
        self.buttonBox.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 75 9pt \"Calibri\";\n"
"    font-weight: bold;\n"
"    background: gray;\n"
"    color: white;\n"
"\n"
"    border-radius: 0px;\n"
"    \n"
"    width: 120px;\n"
"    height: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background:  #595959;\n"
"    color: gray;\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"    background: gray;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: gray;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: lightgray;\n"
"    color: black;\n"
"    border-width: 3px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(co_socket_type_and_num_select)
        QtCore.QMetaObject.connectSlotsByName(co_socket_type_and_num_select)

    def retranslateUi(self, co_socket_type_and_num_select):
        _translate = QtCore.QCoreApplication.translate
        co_socket_type_and_num_select.setWindowTitle(_translate("co_socket_type_and_num_select", "Dialog"))
        self.socket_type_label.setText(_translate("co_socket_type_and_num_select", "Socket Type"))
        self.socket_num_label.setText(_translate("co_socket_type_and_num_select", "Channel Number"))
        self.socket_num_reduce.setText(_translate("co_socket_type_and_num_select", "-"))
        self.socket_num_edit.setText(_translate("co_socket_type_and_num_select", "1"))
        self.socket_num_edit.setPlaceholderText(_translate("co_socket_type_and_num_select", "1"))
        self.channel_number_add.setText(_translate("co_socket_type_and_num_select", "+"))
