# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_dump.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dump_dialog(object):
    def setupUi(self, dump_dialog):
        dump_dialog.setObjectName("dump_dialog")
        dump_dialog.resize(402, 383)
        self.formLayoutWidget = QtWidgets.QWidget(dump_dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 361, 311))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_Audio = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_Audio.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_Audio.setContentsMargins(10, 10, 10, 10)
        self.formLayout_Audio.setHorizontalSpacing(10)
        self.formLayout_Audio.setVerticalSpacing(15)
        self.formLayout_Audio.setObjectName("formLayout_Audio")
        self.label_1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.formLayout_Audio.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.scrollArea = QtWidgets.QScrollArea(self.formLayoutWidget)
        self.scrollArea.setStyleSheet("background-color: #474747;\n"
"border: 0;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 202, 135))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout_Audio.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scrollArea)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.formLayout_Audio.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_time_list = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_time_list.sizePolicy().hasHeightForWidth())
        self.comboBox_time_list.setSizePolicy(sizePolicy)
        self.comboBox_time_list.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_time_list.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_time_list.setFont(font)
        self.comboBox_time_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox_time_list.setObjectName("comboBox_time_list")
        self.formLayout_Audio.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_time_list)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.formLayout_Audio.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_path = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_path.setSizePolicy(sizePolicy)
        self.lineEdit_path.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_path.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_path.setFont(font)
        self.lineEdit_path.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.formLayout_Audio.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_path)
        self.open = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open.sizePolicy().hasHeightForWidth())
        self.open.setSizePolicy(sizePolicy)
        self.open.setMinimumSize(QtCore.QSize(0, 15))
        self.open.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.open.setFont(font)
        self.open.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.open.setObjectName("open")
        self.formLayout_Audio.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.open)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.formLayout_Audio.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.checkBox_dump = QtWidgets.QCheckBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.checkBox_dump.setFont(font)
        self.checkBox_dump.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.checkBox_dump.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_dump.setAutoFillBackground(False)
        self.checkBox_dump.setStyleSheet("QCheckBox::indicator {\n"
"    spacing: 5px;\n"
"    width:                  15px;\n"
"    height:                 15px;\n"
"    border-radius:          3px;\n"
"}\n"
" \n"
"QCheckBox::indicator:checked {\n"
"    background-color:       #494949;\n"
"    border:                 3px solid white;\n"
"}\n"
" \n"
"QCheckBox::indicator:unchecked {\n"
"    background-color:       white;\n"
"    border:                 3px solid white;\n"
"}")
        self.checkBox_dump.setText("")
        self.checkBox_dump.setCheckable(True)
        self.checkBox_dump.setTristate(False)
        self.checkBox_dump.setObjectName("checkBox_dump")
        self.formLayout_Audio.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_dump)
        self.label_4 = QtWidgets.QLabel(dump_dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(dump_dialog)
        QtCore.QMetaObject.connectSlotsByName(dump_dialog)

    def retranslateUi(self, dump_dialog):
        _translate = QtCore.QCoreApplication.translate
        dump_dialog.setWindowTitle(_translate("dump_dialog", "Dialog"))
        self.label_1.setText(_translate("dump_dialog", "Select AO                          "))
        self.label_2.setText(_translate("dump_dialog", "Select Time"))
        self.label_5.setText(_translate("dump_dialog", "File Directory"))
        self.open.setText(_translate("dump_dialog", "open"))
        self.label_3.setText(_translate("dump_dialog", "Dump"))
