# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\control_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_controlDialog(object):
    def setupUi(self, controlDialog):
        controlDialog.setObjectName("controlDialog")
        controlDialog.setEnabled(True)
        controlDialog.resize(385, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(controlDialog.sizePolicy().hasHeightForWidth())
        controlDialog.setSizePolicy(sizePolicy)
        controlDialog.setMinimumSize(QtCore.QSize(385, 550))
        controlDialog.setMaximumSize(QtCore.QSize(385, 550))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        controlDialog.setFont(font)
        controlDialog.setStyleSheet("QLabel{\n"
"    margin-top:10px;\n"
"}")
        controlDialog.setSizeGripEnabled(False)
        controlDialog.setModal(False)
        self.layoutWidget = QtWidgets.QWidget(controlDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 381, 531))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profile_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.profile_label.setFont(font)
        self.profile_label.setObjectName("profile_label")
        self.verticalLayout.addWidget(self.profile_label)
        self.Group0_Profile = QtWidgets.QGroupBox(self.layoutWidget)
        self.Group0_Profile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group0_Profile.sizePolicy().hasHeightForWidth())
        self.Group0_Profile.setSizePolicy(sizePolicy)
        self.Group0_Profile.setMinimumSize(QtCore.QSize(0, 0))
        self.Group0_Profile.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group0_Profile.setFont(font)
        self.Group0_Profile.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"")
        self.Group0_Profile.setTitle("")
        self.Group0_Profile.setFlat(True)
        self.Group0_Profile.setCheckable(False)
        self.Group0_Profile.setObjectName("Group0_Profile")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Group0_Profile)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 361, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hBoxLayout_Profile = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hBoxLayout_Profile.setContentsMargins(10, 10, 10, 10)
        self.hBoxLayout_Profile.setSpacing(10)
        self.hBoxLayout_Profile.setObjectName("hBoxLayout_Profile")
        self.pushButton_import = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_import.sizePolicy().hasHeightForWidth())
        self.pushButton_import.setSizePolicy(sizePolicy)
        self.pushButton_import.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_import.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.pushButton_import.setObjectName("pushButton_import")
        self.hBoxLayout_Profile.addWidget(self.pushButton_import)
        self.pushButton_save = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.pushButton_save.setObjectName("pushButton_save")
        self.hBoxLayout_Profile.addWidget(self.pushButton_save)
        self.verticalLayout.addWidget(self.Group0_Profile)
        self.platform_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.platform_label.setFont(font)
        self.platform_label.setObjectName("platform_label")
        self.verticalLayout.addWidget(self.platform_label)
        self.Group1_Target = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group1_Target.sizePolicy().hasHeightForWidth())
        self.Group1_Target.setSizePolicy(sizePolicy)
        self.Group1_Target.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group1_Target.setFont(font)
        self.Group1_Target.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group1_Target.setTitle("")
        self.Group1_Target.setFlat(True)
        self.Group1_Target.setObjectName("Group1_Target")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.Group1_Target)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_Target = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_Target.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout_Target.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_Target.setContentsMargins(10, 10, 10, 10)
        self.formLayout_Target.setSpacing(10)
        self.formLayout_Target.setObjectName("formLayout_Target")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setScaledContents(False)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.formLayout_Target.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_targetdevice = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_targetdevice.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_targetdevice.sizePolicy().hasHeightForWidth())
        self.comboBox_targetdevice.setSizePolicy(sizePolicy)
        self.comboBox_targetdevice.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_targetdevice.setMaximumSize(QtCore.QSize(240, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_targetdevice.setFont(font)
        self.comboBox_targetdevice.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}\n"
"\n"
"QComboBox::item:!enabled\n"
"{\n"
"    color: gray;\n"
"}")
        self.comboBox_targetdevice.setObjectName("comboBox_targetdevice")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.comboBox_targetdevice.addItem("")
        self.formLayout_Target.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_targetdevice)
        self.verticalLayout.addWidget(self.Group1_Target)
        self.communication_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.communication_label.setFont(font)
        self.communication_label.setObjectName("communication_label")
        self.verticalLayout.addWidget(self.communication_label)
        self.Group2_Audio = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group2_Audio.sizePolicy().hasHeightForWidth())
        self.Group2_Audio.setSizePolicy(sizePolicy)
        self.Group2_Audio.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group2_Audio.setFont(font)
        self.Group2_Audio.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group2_Audio.setTitle("")
        self.Group2_Audio.setFlat(True)
        self.Group2_Audio.setCheckable(False)
        self.Group2_Audio.setObjectName("Group2_Audio")
        self.formLayoutWidget = QtWidgets.QWidget(self.Group2_Audio)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_Audio = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_Audio.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_Audio.setContentsMargins(10, 10, 10, 10)
        self.formLayout_Audio.setSpacing(10)
        self.formLayout_Audio.setObjectName("formLayout_Audio")
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setScaledContents(False)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.formLayout_Audio.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.comboBox_driver_list = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_driver_list.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_driver_list.sizePolicy().hasHeightForWidth())
        self.comboBox_driver_list.setSizePolicy(sizePolicy)
        self.comboBox_driver_list.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_driver_list.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_driver_list.setFont(font)
        self.comboBox_driver_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox_driver_list.setObjectName("comboBox_driver_list")
        self.formLayout_Audio.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_driver_list)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setScaledContents(False)
        self.label_22.setWordWrap(False)
        self.label_22.setObjectName("label_22")
        self.formLayout_Audio.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.comboBox_input_list = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_input_list.sizePolicy().hasHeightForWidth())
        self.comboBox_input_list.setSizePolicy(sizePolicy)
        self.comboBox_input_list.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_input_list.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_input_list.setFont(font)
        self.comboBox_input_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox_input_list.setObjectName("comboBox_input_list")
        self.formLayout_Audio.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_input_list)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setScaledContents(False)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.formLayout_Audio.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.comboBox_output_list = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_output_list.sizePolicy().hasHeightForWidth())
        self.comboBox_output_list.setSizePolicy(sizePolicy)
        self.comboBox_output_list.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_output_list.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_output_list.setFont(font)
        self.comboBox_output_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox_output_list.setObjectName("comboBox_output_list")
        self.formLayout_Audio.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_output_list)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setScaledContents(False)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.formLayout_Audio.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.comboBox_sr_list = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_sr_list.sizePolicy().hasHeightForWidth())
        self.comboBox_sr_list.setSizePolicy(sizePolicy)
        self.comboBox_sr_list.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_sr_list.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_sr_list.setFont(font)
        self.comboBox_sr_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox_sr_list.setFrame(True)
        self.comboBox_sr_list.setObjectName("comboBox_sr_list")
        self.formLayout_Audio.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_sr_list)
        self.pushButton_update = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update.sizePolicy().hasHeightForWidth())
        self.pushButton_update.setSizePolicy(sizePolicy)
        self.pushButton_update.setMinimumSize(QtCore.QSize(0, 15))
        self.pushButton_update.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_update.setFont(font)
        self.pushButton_update.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.pushButton_update.setObjectName("pushButton_update")
        self.formLayout_Audio.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_update)
        self.verticalLayout.addWidget(self.Group2_Audio)
        self.Group3_Network = QtWidgets.QGroupBox(self.layoutWidget)
        self.Group3_Network.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group3_Network.sizePolicy().hasHeightForWidth())
        self.Group3_Network.setSizePolicy(sizePolicy)
        self.Group3_Network.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group3_Network.setFont(font)
        self.Group3_Network.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group3_Network.setTitle("")
        self.Group3_Network.setFlat(True)
        self.Group3_Network.setObjectName("Group3_Network")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.Group3_Network)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 361, 202))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_Network = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_Network.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_Network.setContentsMargins(10, 10, 10, 10)
        self.formLayout_Network.setSpacing(10)
        self.formLayout_Network.setObjectName("formLayout_Network")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setScaledContents(False)
        self.label_16.setWordWrap(False)
        self.label_16.setObjectName("label_16")
        self.formLayout_Network.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_path = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_path.setSizePolicy(sizePolicy)
        self.lineEdit_path.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_path.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_path.setFont(font)
        self.lineEdit_path.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.formLayout_Network.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_path)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(False)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.formLayout_Network.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.hostname_layout = QtWidgets.QHBoxLayout()
        self.hostname_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.hostname_layout.setSpacing(4)
        self.hostname_layout.setObjectName("hostname_layout")
        self.lineEdit_hostname_1 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_hostname_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_hostname_1.setSizePolicy(sizePolicy)
        self.lineEdit_hostname_1.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_hostname_1.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_hostname_1.setFont(font)
        self.lineEdit_hostname_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_hostname_1.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_hostname_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_hostname_1.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_hostname_1.setObjectName("lineEdit_hostname_1")
        self.hostname_layout.addWidget(self.lineEdit_hostname_1)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setScaledContents(False)
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName("label_17")
        self.hostname_layout.addWidget(self.label_17)
        self.lineEdit_hostname_2 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_hostname_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_hostname_2.setSizePolicy(sizePolicy)
        self.lineEdit_hostname_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_hostname_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_hostname_2.setFont(font)
        self.lineEdit_hostname_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_hostname_2.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_hostname_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_hostname_2.setObjectName("lineEdit_hostname_2")
        self.hostname_layout.addWidget(self.lineEdit_hostname_2)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setScaledContents(False)
        self.label_18.setWordWrap(False)
        self.label_18.setObjectName("label_18")
        self.hostname_layout.addWidget(self.label_18)
        self.lineEdit_hostname_3 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_hostname_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_hostname_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_hostname_3.setFont(font)
        self.lineEdit_hostname_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_hostname_3.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_hostname_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_hostname_3.setObjectName("lineEdit_hostname_3")
        self.hostname_layout.addWidget(self.lineEdit_hostname_3)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setScaledContents(False)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.hostname_layout.addWidget(self.label_19)
        self.lineEdit_hostname_4 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_hostname_4.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_hostname_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_hostname_4.setFont(font)
        self.lineEdit_hostname_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_hostname_4.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_hostname_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_hostname_4.setObjectName("lineEdit_hostname_4")
        self.hostname_layout.addWidget(self.lineEdit_hostname_4)
        self.formLayout_Network.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hostname_layout)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.formLayout_Network.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_freeports = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_freeports.sizePolicy().hasHeightForWidth())
        self.lineEdit_freeports.setSizePolicy(sizePolicy)
        self.lineEdit_freeports.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_freeports.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_freeports.setFont(font)
        self.lineEdit_freeports.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_freeports.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_freeports.setObjectName("lineEdit_freeports")
        self.formLayout_Network.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_freeports)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setScaledContents(False)
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.formLayout_Network.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_username = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_username.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_username.sizePolicy().hasHeightForWidth())
        self.lineEdit_username.setSizePolicy(sizePolicy)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_username.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_username.setMaxLength(64)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout_Network.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_username)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setScaledContents(False)
        self.label_15.setWordWrap(False)
        self.label_15.setObjectName("label_15")
        self.formLayout_Network.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_password = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_password.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_password.sizePolicy().hasHeightForWidth())
        self.lineEdit_password.setSizePolicy(sizePolicy)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_password.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_password.setMaxLength(64)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout_Network.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.verticalLayout.addWidget(self.Group3_Network)
        self.Group5_Connection = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group5_Connection.sizePolicy().hasHeightForWidth())
        self.Group5_Connection.setSizePolicy(sizePolicy)
        self.Group5_Connection.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group5_Connection.setFont(font)
        self.Group5_Connection.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group5_Connection.setTitle("")
        self.Group5_Connection.setFlat(True)
        self.Group5_Connection.setCheckable(False)
        self.Group5_Connection.setObjectName("Group5_Connection")
        self.layoutWidget1 = QtWidgets.QWidget(self.Group5_Connection)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 361, 311))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(10, 20, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_54.setFont(font)
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_54.setTextFormat(QtCore.Qt.AutoText)
        self.label_54.setScaledContents(False)
        self.label_54.setWordWrap(False)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout.addWidget(self.label_54)
        self.comboBox_driver_list_5 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_driver_list_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_driver_list_5.sizePolicy().hasHeightForWidth())
        self.comboBox_driver_list_5.setSizePolicy(sizePolicy)
        self.comboBox_driver_list_5.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_driver_list_5.setMaximumSize(QtCore.QSize(240, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_driver_list_5.setFont(font)
        self.comboBox_driver_list_5.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}\n"
"\n"
"QComboBox::item:!enabled\n"
"{\n"
"    color: gray;\n"
"}")
        self.comboBox_driver_list_5.setObjectName("comboBox_driver_list_5")
        self.comboBox_driver_list_5.addItem("")
        self.comboBox_driver_list_5.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_driver_list_5)
        self.comboBox_driver_list_6 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_driver_list_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_driver_list_6.sizePolicy().hasHeightForWidth())
        self.comboBox_driver_list_6.setSizePolicy(sizePolicy)
        self.comboBox_driver_list_6.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_driver_list_6.setMaximumSize(QtCore.QSize(240, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_driver_list_6.setFont(font)
        self.comboBox_driver_list_6.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}\n"
"\n"
"QComboBox::item:!enabled\n"
"{\n"
"    color: gray;\n"
"}")
        self.comboBox_driver_list_6.setObjectName("comboBox_driver_list_6")
        self.comboBox_driver_list_6.addItem("")
        self.comboBox_driver_list_6.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_driver_list_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout_Components = QtWidgets.QFormLayout()
        self.formLayout_Components.setContentsMargins(10, 0, 10, 10)
        self.formLayout_Components.setHorizontalSpacing(10)
        self.formLayout_Components.setVerticalSpacing(5)
        self.formLayout_Components.setObjectName("formLayout_Components")
        self.Rate = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Rate.setFont(font)
        self.Rate.setObjectName("Rate")
        self.formLayout_Components.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Rate)
        self.Rate_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rate_comboBox.sizePolicy().hasHeightForWidth())
        self.Rate_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Rate_comboBox.setFont(font)
        self.Rate_comboBox.setObjectName("Rate_comboBox")
        self.Rate_comboBox.addItem("")
        self.formLayout_Components.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Rate_comboBox)
        self.Parity = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Parity.setFont(font)
        self.Parity.setObjectName("Parity")
        self.formLayout_Components.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Parity)
        self.Parity_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Parity_comboBox.sizePolicy().hasHeightForWidth())
        self.Parity_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Parity_comboBox.setFont(font)
        self.Parity_comboBox.setObjectName("Parity_comboBox")
        self.Parity_comboBox.addItem("")
        self.formLayout_Components.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Parity_comboBox)
        self.Bits = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Bits.setFont(font)
        self.Bits.setObjectName("Bits")
        self.formLayout_Components.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Bits)
        self.Bites_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bites_comboBox.sizePolicy().hasHeightForWidth())
        self.Bites_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Bites_comboBox.setFont(font)
        self.Bites_comboBox.setObjectName("Bites_comboBox")
        self.Bites_comboBox.addItem("")
        self.formLayout_Components.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.Bites_comboBox)
        self.Connection_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connection_comboBox.sizePolicy().hasHeightForWidth())
        self.Connection_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Connection_comboBox.setFont(font)
        self.Connection_comboBox.setObjectName("Connection_comboBox")
        self.Connection_comboBox.addItem("")
        self.formLayout_Components.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Connection_comboBox)
        self.Connection = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Connection.setFont(font)
        self.Connection.setObjectName("Connection")
        self.formLayout_Components.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Connection)
        self.Vid = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Vid.sizePolicy().hasHeightForWidth())
        self.Vid.setSizePolicy(sizePolicy)
        self.Vid.setMinimumSize(QtCore.QSize(54, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Vid.setFont(font)
        self.Vid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Vid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Vid.setTextFormat(QtCore.Qt.AutoText)
        self.Vid.setScaledContents(False)
        self.Vid.setWordWrap(False)
        self.Vid.setObjectName("Vid")
        self.formLayout_Components.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Vid)
        self.lineEdit_vid = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vid.sizePolicy().hasHeightForWidth())
        self.lineEdit_vid.setSizePolicy(sizePolicy)
        self.lineEdit_vid.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_vid.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_vid.setFont(font)
        self.lineEdit_vid.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_vid.setObjectName("lineEdit_vid")
        self.formLayout_Components.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_vid)
        self.Pid = QtWidgets.QLabel(self.layoutWidget1)
        self.Pid.setMinimumSize(QtCore.QSize(54, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Pid.setFont(font)
        self.Pid.setObjectName("Pid")
        self.formLayout_Components.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Pid)
        self.lineEdit_pid = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pid.sizePolicy().hasHeightForWidth())
        self.lineEdit_pid.setSizePolicy(sizePolicy)
        self.lineEdit_pid.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_pid.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_pid.setFont(font)
        self.lineEdit_pid.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.lineEdit_pid.setObjectName("lineEdit_pid")
        self.formLayout_Components.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pid)
        self.Port = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Port.setFont(font)
        self.Port.setObjectName("Port")
        self.formLayout_Components.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Port)
        self.Port_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Port_comboBox.sizePolicy().hasHeightForWidth())
        self.Port_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Port_comboBox.setFont(font)
        self.Port_comboBox.setObjectName("Port_comboBox")
        self.Port_comboBox.addItem("")
        self.formLayout_Components.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Port_comboBox)
        self.Engine = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Engine.setFont(font)
        self.Engine.setObjectName("Engine")
        self.formLayout_Components.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Engine)
        self.Engine_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Engine_comboBox.sizePolicy().hasHeightForWidth())
        self.Engine_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Engine_comboBox.setFont(font)
        self.Engine_comboBox.setObjectName("Engine_comboBox")
        self.Engine_comboBox.addItem("")
        self.Engine_comboBox.addItem("")
        self.Engine_comboBox.addItem("")
        self.Engine_comboBox.addItem("")
        self.Engine_comboBox.addItem("")
        self.formLayout_Components.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Engine_comboBox)
        self.verticalLayout_2.addLayout(self.formLayout_Components)
        self.verticalLayout.addWidget(self.Group5_Connection)
        self.Group6_S7 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group6_S7.sizePolicy().hasHeightForWidth())
        self.Group6_S7.setSizePolicy(sizePolicy)
        self.Group6_S7.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group6_S7.setFont(font)
        self.Group6_S7.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group6_S7.setTitle("")
        self.Group6_S7.setFlat(True)
        self.Group6_S7.setCheckable(False)
        self.Group6_S7.setObjectName("Group6_S7")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.Group6_S7)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 361, 112))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_S7 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_S7.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_S7.setContentsMargins(10, 10, 10, 10)
        self.formLayout_S7.setSpacing(10)
        self.formLayout_S7.setObjectName("formLayout_S7")
        self.transports = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.transports.setFont(font)
        self.transports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.transports.setFrameShadow(QtWidgets.QFrame.Plain)
        self.transports.setTextFormat(QtCore.Qt.AutoText)
        self.transports.setScaledContents(False)
        self.transports.setWordWrap(False)
        self.transports.setObjectName("transports")
        self.formLayout_S7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.transports)
        self.transports_list = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.transports_list.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transports_list.sizePolicy().hasHeightForWidth())
        self.transports_list.setSizePolicy(sizePolicy)
        self.transports_list.setMinimumSize(QtCore.QSize(0, 0))
        self.transports_list.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.transports_list.setFont(font)
        self.transports_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.transports_list.setObjectName("transports_list")
        self.formLayout_S7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.transports_list)
        self.header = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.header.setFont(font)
        self.header.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.header.setFrameShadow(QtWidgets.QFrame.Plain)
        self.header.setTextFormat(QtCore.Qt.AutoText)
        self.header.setScaledContents(False)
        self.header.setWordWrap(False)
        self.header.setObjectName("header")
        self.formLayout_S7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.header)
        self.header_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_lineEdit.sizePolicy().hasHeightForWidth())
        self.header_lineEdit.setSizePolicy(sizePolicy)
        self.header_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.header_lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.header_lineEdit.setFont(font)
        self.header_lineEdit.setStyleSheet("QLineEdit{\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: gray;\n"
"}\n"
"QLineEdit::enabled {\n"
"    color: black;\n"
"}")
        self.header_lineEdit.setObjectName("header_lineEdit")
        self.formLayout_S7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.header_lineEdit)
        self.s7_rate = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.s7_rate.setFont(font)
        self.s7_rate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s7_rate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.s7_rate.setTextFormat(QtCore.Qt.AutoText)
        self.s7_rate.setScaledContents(False)
        self.s7_rate.setWordWrap(False)
        self.s7_rate.setObjectName("s7_rate")
        self.formLayout_S7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.s7_rate)
        self.s7_rate_list = QtWidgets.QComboBox(self.formLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s7_rate_list.sizePolicy().hasHeightForWidth())
        self.s7_rate_list.setSizePolicy(sizePolicy)
        self.s7_rate_list.setMinimumSize(QtCore.QSize(0, 0))
        self.s7_rate_list.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.s7_rate_list.setFont(font)
        self.s7_rate_list.setStyleSheet("QComboBox\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.s7_rate_list.setFrame(True)
        self.s7_rate_list.setObjectName("s7_rate_list")
        self.s7_rate_list.addItem("")
        self.s7_rate_list.addItem("")
        self.formLayout_S7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s7_rate_list)
        self.verticalLayout.addWidget(self.Group6_S7)
        self.connect_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.connect_label.setFont(font)
        self.connect_label.setObjectName("connect_label")
        self.verticalLayout.addWidget(self.connect_label)
        self.Group4_Editor = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group4_Editor.sizePolicy().hasHeightForWidth())
        self.Group4_Editor.setSizePolicy(sizePolicy)
        self.Group4_Editor.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group4_Editor.setFont(font)
        self.Group4_Editor.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group4_Editor.setTitle("")
        self.Group4_Editor.setFlat(True)
        self.Group4_Editor.setObjectName("Group4_Editor")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.Group4_Editor)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 361, 100))
        font = QtGui.QFont()
        font.setFamily("PMingLiU")
        font.setPointSize(9)
        self.formLayoutWidget_3.setFont(font)
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_Editor = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_Editor.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout_Editor.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_Editor.setContentsMargins(10, 10, 10, 10)
        self.formLayout_Editor.setSpacing(10)
        self.formLayout_Editor.setObjectName("formLayout_Editor")
        self.h_layout_engine_path = QtWidgets.QHBoxLayout()
        self.h_layout_engine_path.setObjectName("h_layout_engine_path")
        self.label_engine_path = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_engine_path.setFont(font)
        self.label_engine_path.setObjectName("label_engine_path")
        self.h_layout_engine_path.addWidget(self.label_engine_path)
        self.line_edit_engine_path = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_engine_path.sizePolicy().hasHeightForWidth())
        self.line_edit_engine_path.setSizePolicy(sizePolicy)
        self.line_edit_engine_path.setMinimumSize(QtCore.QSize(175, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.line_edit_engine_path.setFont(font)
        self.line_edit_engine_path.setReadOnly(True)
        self.line_edit_engine_path.setObjectName("line_edit_engine_path")
        self.h_layout_engine_path.addWidget(self.line_edit_engine_path)
        self.push_button_browse_engine_path = QtWidgets.QPushButton(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.push_button_browse_engine_path.setFont(font)
        self.push_button_browse_engine_path.setMinimumSize(QtCore.QSize(0, 30))
        self.push_button_browse_engine_path.setObjectName("push_button_browse_engine_path")
        self.h_layout_engine_path.addWidget(self.push_button_browse_engine_path)
        self.formLayout_Editor.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.h_layout_engine_path)
        self.h_layout_connect_to_engine = QtWidgets.QHBoxLayout()
        self.h_layout_connect_to_engine.setObjectName("h_layout_connect_to_engine")
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setTextFormat(QtCore.Qt.AutoText)
        self.label_31.setScaledContents(False)
        self.label_31.setWordWrap(False)
        self.label_31.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_31.setObjectName("label_31")
        self.h_layout_connect_to_engine.addWidget(self.label_31)
        self.checkBox_dsp = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.checkBox_dsp.setFont(font)
        self.checkBox_dsp.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.checkBox_dsp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_dsp.setAutoFillBackground(False)
        self.checkBox_dsp.setStyleSheet("\n"
"              QCheckBox::indicator {\n"
"              spacing: 5px;\n"
"              width: 15px;\n"
"              height: 15px;\n"
"              border-radius: 3px;\n"
"              }\n"
"\n"
"              QCheckBox::indicator:checked {\n"
"              background-color: white;\n"
"              border: 3px solid white;\n"
"              image: url(../resources/checked.png);\n"
"              }\n"
"\n"
"              QCheckBox::indicator:unchecked {\n"
"              background-color: white;\n"
"              border: 3px solid white;\n"
"              }\n"
"             ")
        self.checkBox_dsp.setText("")
        self.checkBox_dsp.setCheckable(True)
        self.checkBox_dsp.setTristate(False)
        self.checkBox_dsp.setObjectName("checkBox_dsp")
        self.h_layout_connect_to_engine.addWidget(self.checkBox_dsp)
        self.debug_mode_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.debug_mode_label.setVisible(False)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.debug_mode_label.setFont(font)
        self.debug_mode_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.debug_mode_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.debug_mode_label.setTextFormat(QtCore.Qt.AutoText)
        self.debug_mode_label.setScaledContents(False)
        self.debug_mode_label.setWordWrap(False)
        self.debug_mode_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.debug_mode_label.setObjectName("debug_mode_label")
        self.h_layout_connect_to_engine.addWidget(self.debug_mode_label)
        self.debug_mode_check_box = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.debug_mode_check_box.setVisible(False)
        self.debug_mode_check_box.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.debug_mode_check_box.setFont(font)
        self.debug_mode_check_box.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.debug_mode_check_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.debug_mode_check_box.setAutoFillBackground(False)
        self.debug_mode_check_box.setStyleSheet("\n"
"              QCheckBox::indicator {\n"
"              spacing: 5px;\n"
"              width: 15px;\n"
"              height: 15px;\n"
"              border-radius: 3px;\n"
"              }\n"
"\n"
"              QCheckBox::indicator:checked {\n"
"              background-color: white;\n"
"              border: 3px solid white;\n"
"              image: url(../resources/checked.png);\n"
"              }\n"
"\n"
"              QCheckBox::indicator:unchecked {\n"
"              background-color: white;\n"
"              border: 3px solid white;\n"
"              }\n"
"             ")
        self.debug_mode_check_box.setText("")
        self.debug_mode_check_box.setCheckable(True)
        self.debug_mode_check_box.setTristate(False)
        self.debug_mode_check_box.setObjectName("debug_mode_check_box")
        self.h_layout_connect_to_engine.addWidget(self.debug_mode_check_box)
        self.formLayout_Editor.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.h_layout_connect_to_engine)
        self.verticalLayout.addWidget(self.Group4_Editor)

        self.retranslateUi(controlDialog)
        QtCore.QMetaObject.connectSlotsByName(controlDialog)

    def retranslateUi(self, controlDialog):
        _translate = QtCore.QCoreApplication.translate
        controlDialog.setWindowTitle(_translate("controlDialog", "Settings"))
        self.profile_label.setText(_translate("controlDialog", "Profile Settings"))
        self.pushButton_import.setText(_translate("controlDialog", "Import"))
        self.pushButton_save.setText(_translate("controlDialog", "Save"))
        self.platform_label.setText(_translate("controlDialog", "Target Platform"))
        self.label_11.setText(_translate("controlDialog", "Select Device:"))
        self.comboBox_targetdevice.setItemText(0, _translate("controlDialog", "PC"))
        self.comboBox_targetdevice.setItemText(1, _translate("controlDialog", "i.MX8"))
        self.comboBox_targetdevice.setItemText(2, _translate("controlDialog", "Linux"))
        self.comboBox_targetdevice.setItemText(3, _translate("controlDialog", "AmLogic A113D/X"))
        self.comboBox_targetdevice.setItemText(4, _translate("controlDialog", "Linkplay A98"))
        self.comboBox_targetdevice.setItemText(5, _translate("controlDialog", "Raspberry Pi"))
        self.comboBox_targetdevice.setItemText(6, _translate("controlDialog", "QCS40X"))
        self.comboBox_targetdevice.setItemText(7, _translate("controlDialog", "Cortex-M"))
        self.comboBox_targetdevice.setItemText(8, _translate("controlDialog", "Airoha AB1585"))
        self.comboBox_targetdevice.setItemText(9, _translate("controlDialog", "Airoha AB1565"))
        self.comboBox_targetdevice.setItemText(10, _translate("controlDialog", "TCP"))
        self.comboBox_targetdevice.setItemText(11, _translate("controlDialog", "Flow EVK"))
        self.comboBox_targetdevice.setItemText(12, _translate("controlDialog", "GX8008C"))
        self.comboBox_targetdevice.setItemText(13, _translate("controlDialog", "S7"))
        self.communication_label.setText(_translate("controlDialog", "Communication settings"))
        self.label_21.setText(_translate("controlDialog", "Driver Select:"))
        self.label_22.setText(_translate("controlDialog", "Input Device:"))
        self.label_23.setText(_translate("controlDialog", "Output Device:"))
        self.label_24.setText(_translate("controlDialog", "Sample Rate:"))
        self.pushButton_update.setText(_translate("controlDialog", "Refresh Audio Device"))
        self.label_16.setText(_translate("controlDialog", "Config Path:"))
        self.label_12.setText(_translate("controlDialog", "Host Name:"))
        self.lineEdit_hostname_1.setInputMask(_translate("controlDialog", "000"))
        self.lineEdit_hostname_1.setText(_translate("controlDialog", "127"))
        self.lineEdit_hostname_1.setPlaceholderText(_translate("controlDialog", "127"))
        self.label_17.setText(_translate("controlDialog", "."))
        self.lineEdit_hostname_2.setInputMask(_translate("controlDialog", "000"))
        self.lineEdit_hostname_2.setText(_translate("controlDialog", "000"))
        self.lineEdit_hostname_2.setPlaceholderText(_translate("controlDialog", "000"))
        self.label_18.setText(_translate("controlDialog", "."))
        self.lineEdit_hostname_3.setInputMask(_translate("controlDialog", "000"))
        self.lineEdit_hostname_3.setText(_translate("controlDialog", "000"))
        self.lineEdit_hostname_3.setPlaceholderText(_translate("controlDialog", "000"))
        self.label_19.setText(_translate("controlDialog", "."))
        self.lineEdit_hostname_4.setInputMask(_translate("controlDialog", "000"))
        self.lineEdit_hostname_4.setText(_translate("controlDialog", "001"))
        self.lineEdit_hostname_4.setPlaceholderText(_translate("controlDialog", "001"))
        self.label_13.setText(_translate("controlDialog", "Free Ports:"))
        self.lineEdit_freeports.setInputMask(_translate("controlDialog", "99999"))
        self.lineEdit_freeports.setText(_translate("controlDialog", "54010"))
        self.lineEdit_freeports.setPlaceholderText(_translate("controlDialog", "54010"))
        self.label_14.setText(_translate("controlDialog", "User Name:"))
        self.lineEdit_username.setText(_translate("controlDialog", "localhost"))
        self.lineEdit_username.setPlaceholderText(_translate("controlDialog", "localhost"))
        self.label_15.setText(_translate("controlDialog", "Password:"))
        self.lineEdit_password.setText(_translate("controlDialog", "0000"))
        self.label_54.setText(_translate("controlDialog", "Interface："))
        self.comboBox_driver_list_5.setItemText(0, _translate("controlDialog", "USB"))
        self.comboBox_driver_list_5.setItemText(1, _translate("controlDialog", "UART"))
        self.comboBox_driver_list_6.setItemText(0, _translate("controlDialog", "UART"))
        self.comboBox_driver_list_6.setItemText(1, _translate("controlDialog", "USB"))
        self.Rate.setText(_translate("controlDialog", "Baud Rate:"))
        self.Rate_comboBox.setItemText(0, _translate("controlDialog", "115200"))
        self.Parity.setText(_translate("controlDialog", "Parity:"))
        self.Parity_comboBox.setItemText(0, _translate("controlDialog", "None"))
        self.Bits.setText(_translate("controlDialog", "Stop bits"))
        self.Bites_comboBox.setItemText(0, _translate("controlDialog", "1"))
        self.Connection_comboBox.setItemText(0, _translate("controlDialog", "RS232"))
        self.Connection.setText(_translate("controlDialog", "Connection:"))
        self.Vid.setText(_translate("controlDialog", "VID:"))
        self.Pid.setText(_translate("controlDialog", "PID:"))
        self.Port.setText(_translate("controlDialog", "COM PORT:"))
        self.Port_comboBox.setItemText(0, _translate("controlDialog", "COM333"))
        self.Engine.setText(_translate("controlDialog", "Engine："))
        self.Engine_comboBox.setItemText(0, _translate("controlDialog", "USB_TX"))
        self.Engine_comboBox.setItemText(1, _translate("controlDialog", "USB_RX"))
        self.Engine_comboBox.setItemText(2, _translate("controlDialog", "HFP_TX"))
        self.Engine_comboBox.setItemText(3, _translate("controlDialog", "HFP_RX"))
        self.Engine_comboBox.setItemText(4, _translate("controlDialog", "A2DP"))
        self.transports.setText(_translate("controlDialog", "usb port："))
        self.header.setText(_translate("controlDialog", "instance id："))
        self.header_lineEdit.setText(_translate("controlDialog", "0x04065"))
        self.s7_rate.setText(_translate("controlDialog", "Sample Rate:"))
        self.s7_rate_list.setItemText(0, _translate("controlDialog", "44100"))
        self.s7_rate_list.setItemText(1, _translate("controlDialog", "48000"))
        self.connect_label.setText(_translate("controlDialog", "Connect"))
        self.label_engine_path.setText(_translate("controlDialog", "Engine Path:"))
        self.push_button_browse_engine_path.setText(_translate("controlDialog", "Select"))
        self.label_31.setText(_translate("controlDialog", "Connect To Engine:"))
        self.debug_mode_label.setText(_translate("controlDialog", "Debug:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    controlDialog = QtWidgets.QDialog()
    ui = Ui_controlDialog()
    ui.setupUi(controlDialog)
    controlDialog.show()
    sys.exit(app.exec_())
