# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\custom_ao_builder.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 840)
        Dialog.setMinimumSize(QtCore.QSize(900, 840))
        Dialog.setMaximumSize(QtCore.QSize(1920, 1080))
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"    border: 1px solid #404040;\n"
"    border-radius: 6px;\n"
"}")
        self.add_ao_btn = QtWidgets.QPushButton(Dialog)
        self.add_ao_btn.setGeometry(QtCore.QRect(20, 20, 41, 23))
        self.add_ao_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.add_ao_btn.setObjectName("add_ao_btn")
        self.remove_ao_btn = QtWidgets.QPushButton(Dialog)
        self.remove_ao_btn.setEnabled(False)
        self.remove_ao_btn.setGeometry(QtCore.QRect(90, 20, 41, 23))
        self.remove_ao_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.remove_ao_btn.setObjectName("remove_ao_btn")
        self.aos_list_widget = QtWidgets.QListWidget(Dialog)
        self.aos_list_widget.setGeometry(QtCore.QRect(20, 60, 121, 641))
        self.aos_list_widget.setAcceptDrops(True)
        self.aos_list_widget.setStyleSheet("QListWidget {\n"
"    background-color: #323232;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"/* Scrollbar styling */\n"
"QListWidget QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #2b2b2b;\n"
"    width: 10px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QListWidget QScrollBar::handle:vertical {\n"
"    background: #4d4d4d;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget QScrollBar::handle:vertical:hover {\n"
"    background: #5a5a5a;\n"
"}\n"
"\n"
"QListWidget QScrollBar::add-line:vertical,\n"
"QListWidget QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"QListWidget QScrollBar::add-page:vertical,\n"
"QListWidget QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.aos_list_widget.setDragEnabled(True)
        self.aos_list_widget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.aos_list_widget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.aos_list_widget.setObjectName("aos_list_widget")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setGeometry(QtCore.QRect(200, 30, 47, 12))
        self.name_label.setObjectName("name_label")
        self.name_line_edit = QtWidgets.QLineEdit(Dialog)
        self.name_line_edit.setGeometry(QtCore.QRect(240, 20, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_line_edit.setFont(font)
        self.name_line_edit.setObjectName("name_line_edit")
        self.description_label = QtWidgets.QLabel(Dialog)
        self.description_label.setGeometry(QtCore.QRect(170, 90, 71, 16))
        self.description_label.setObjectName("description_label")
        self.description_line_edit = QtWidgets.QTextEdit(Dialog)
        self.description_line_edit.setGeometry(QtCore.QRect(240, 90, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.description_line_edit.setFont(font)
        self.description_line_edit.setObjectName("description_line_edit")
        self.display_name_label = QtWidgets.QLabel(Dialog)
        self.display_name_label.setGeometry(QtCore.QRect(160, 60, 81, 16))
        self.display_name_label.setObjectName("display_name_label")
        self.display_name_line_edit = QtWidgets.QLineEdit(Dialog)
        self.display_name_line_edit.setGeometry(QtCore.QRect(240, 60, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.display_name_line_edit.setFont(font)
        self.display_name_line_edit.setObjectName("display_name_line_edit")
        self.is_float_point_label = QtWidgets.QLabel(Dialog)
        self.is_float_point_label.setGeometry(QtCore.QRect(160, 270, 91, 16))
        self.is_float_point_label.setObjectName("is_float_point_label")
        self.is_float_point_check_box = QtWidgets.QCheckBox(Dialog)
        self.is_float_point_check_box.setGeometry(QtCore.QRect(240, 270, 73, 16))
        self.is_float_point_check_box.setStyleSheet("QCheckBox {\n"
"                    color: white;\n"
"                    font-family: Calibri;\n"
"                }\n"
"                QCheckBox::indicator{\n"
"                    border: 2px solid #b1b1b1;\n"
"                    background-color: white;\n"
"                }\n"
"                \n"
"                QCheckBox::indicator:checked {\n"
"                    background-color: black;\n"
"                }\n"
"                \n"
"                \n"
"                QCheckBox::indicator:unchecked {\n"
"                    background-color: white;\n"
"                }")
        self.is_float_point_check_box.setText("")
        self.is_float_point_check_box.setObjectName("is_float_point_check_box")
        self.addition_type_label = QtWidgets.QLabel(Dialog)
        self.addition_type_label.setGeometry(QtCore.QRect(200, 310, 41, 16))
        self.addition_type_label.setObjectName("addition_type_label")
        self.addition_type_combo_box = QtWidgets.QComboBox(Dialog)
        self.addition_type_combo_box.setGeometry(QtCore.QRect(240, 310, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addition_type_combo_box.setFont(font)
        self.addition_type_combo_box.setStyleSheet("")
        self.addition_type_combo_box.setObjectName("addition_type_combo_box")
        self.collapsible_label = QtWidgets.QLabel(Dialog)
        self.collapsible_label.setGeometry(QtCore.QRect(300, 270, 81, 16))
        self.collapsible_label.setObjectName("collapsible_label")
        self.collapsible_check_box = QtWidgets.QCheckBox(Dialog)
        self.collapsible_check_box.setGeometry(QtCore.QRect(370, 270, 16, 16))
        self.collapsible_check_box.setStyleSheet("QCheckBox {\n"
"                    color: white;\n"
"                    font-family: Calibri;\n"
"                }\n"
"                QCheckBox::indicator{\n"
"                    border: 2px solid #b1b1b1;\n"
"                    background-color: white;\n"
"                }\n"
"                \n"
"                QCheckBox::indicator:checked {\n"
"                    background-color: black;\n"
"                }\n"
"                \n"
"                \n"
"                QCheckBox::indicator:unchecked {\n"
"                    background-color: white;\n"
"                }\n"
"QCheckBox:disabled {background-color:gray;}")
        self.collapsible_check_box.setText("")
        self.collapsible_check_box.setObjectName("collapsible_check_box")
        self.tuning_parameters_label = QtWidgets.QLabel(Dialog)
        self.tuning_parameters_label.setGeometry(QtCore.QRect(170, 455, 111, 41))
        self.tuning_parameters_label.setObjectName("tuning_parameters_label")
        self.supported_platforms_label = QtWidgets.QLabel(Dialog)
        self.supported_platforms_label.setGeometry(QtCore.QRect(170, 410, 101, 41))
        self.supported_platforms_label.setObjectName("supported_platforms_label")
        self.add_tuning_param_btn = QtWidgets.QPushButton(Dialog)
        self.add_tuning_param_btn.setGeometry(QtCore.QRect(250, 470, 41, 23))
        self.add_tuning_param_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.add_tuning_param_btn.setObjectName("add_tuning_param_btn")
        self.remove_tuning_param_btn = QtWidgets.QPushButton(Dialog)
        self.remove_tuning_param_btn.setEnabled(False)
        self.remove_tuning_param_btn.setGeometry(QtCore.QRect(310, 470, 41, 23))
        self.remove_tuning_param_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.remove_tuning_param_btn.setObjectName("remove_tuning_param_btn")
        self.icon_label = QtWidgets.QLabel(Dialog)
        self.icon_label.setGeometry(QtCore.QRect(200, 180, 51, 20))
        self.icon_label.setObjectName("icon_label")
        self.icon_push_btn = QtWidgets.QPushButton(Dialog)
        self.icon_push_btn.setGeometry(QtCore.QRect(240, 210, 75, 21))
        self.icon_push_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.icon_push_btn.setObjectName("icon_push_btn")
        self.icon_line_edit = QtWidgets.QLineEdit(Dialog)
        self.icon_line_edit.setGeometry(QtCore.QRect(240, 180, 241, 20))
        self.icon_line_edit.setReadOnly(True)
        self.icon_line_edit.setObjectName("icon_line_edit")
        self.is_popup_allowed_label = QtWidgets.QLabel(Dialog)
        self.is_popup_allowed_label.setGeometry(QtCore.QRect(410, 255, 111, 41))
        self.is_popup_allowed_label.setObjectName("is_popup_allowed_label")
        self.is_popup_allowed_check_box = QtWidgets.QCheckBox(Dialog)
        self.is_popup_allowed_check_box.setEnabled(False)
        self.is_popup_allowed_check_box.setGeometry(QtCore.QRect(520, 270, 16, 16))
        self.is_popup_allowed_check_box.setStyleSheet("QCheckBox {\n"
"                    color: white;\n"
"                    font-family: Calibri;\n"
"                }\n"
"                QCheckBox::indicator{\n"
"                    border: 2px solid #b1b1b1;\n"
"                    background-color: white;\n"
"                }\n"
"                \n"
"                QCheckBox::indicator:checked {\n"
"                    background-color: black;\n"
"                }\n"
"                \n"
"                \n"
"                QCheckBox::indicator:unchecked {\n"
"                    background-color: white;\n"
"                }")
        self.is_popup_allowed_check_box.setText("")
        self.is_popup_allowed_check_box.setCheckable(True)
        self.is_popup_allowed_check_box.setObjectName("is_popup_allowed_check_box")
        self.num_input_sockets_spin_box = QtWidgets.QSpinBox(Dialog)
        self.num_input_sockets_spin_box.setGeometry(QtCore.QRect(270, 350, 41, 21))
        self.num_input_sockets_spin_box.setMinimumSize(QtCore.QSize(0, 0))
        self.num_input_sockets_spin_box.setStyleSheet("")
        self.num_input_sockets_spin_box.setObjectName("num_input_sockets_spin_box")
        self.num_input_sockets_label = QtWidgets.QLabel(Dialog)
        self.num_input_sockets_label.setGeometry(QtCore.QRect(180, 350, 81, 16))
        self.num_input_sockets_label.setObjectName("num_input_sockets_label")
        self.num_output_sockets_label = QtWidgets.QLabel(Dialog)
        self.num_output_sockets_label.setGeometry(QtCore.QRect(400, 350, 91, 16))
        self.num_output_sockets_label.setObjectName("num_output_sockets_label")
        self.num_output_sockets_spin_box = QtWidgets.QSpinBox(Dialog)
        self.num_output_sockets_spin_box.setGeometry(QtCore.QRect(500, 350, 42, 22))
        self.num_output_sockets_spin_box.setStyleSheet("")
        self.num_output_sockets_spin_box.setObjectName("num_output_sockets_spin_box")
        self.num_inctrl_sockets_label = QtWidgets.QLabel(Dialog)
        self.num_inctrl_sockets_label.setGeometry(QtCore.QRect(160, 380, 111, 16))
        self.num_inctrl_sockets_label.setObjectName("num_inctrl_sockets_label")
        self.num_inctrl_sockets_spin_box = QtWidgets.QSpinBox(Dialog)
        self.num_inctrl_sockets_spin_box.setGeometry(QtCore.QRect(270, 380, 41, 21))
        self.num_inctrl_sockets_spin_box.setMinimumSize(QtCore.QSize(0, 0))
        self.num_inctrl_sockets_spin_box.setStyleSheet("")
        self.num_inctrl_sockets_spin_box.setObjectName("num_inctrl_sockets_spin_box")
        self.num_outctrl_sockets_label = QtWidgets.QLabel(Dialog)
        self.num_outctrl_sockets_label.setGeometry(QtCore.QRect(380, 380, 111, 16))
        self.num_outctrl_sockets_label.setObjectName("num_outctrl_sockets_label")
        self.num_outctrl_sockets_spin_box = QtWidgets.QSpinBox(Dialog)
        self.num_outctrl_sockets_spin_box.setGeometry(QtCore.QRect(500, 380, 42, 22))
        self.num_outctrl_sockets_spin_box.setStyleSheet("")
        self.num_outctrl_sockets_spin_box.setObjectName("num_outctrl_sockets_spin_box")
        self.icon_image = QtWidgets.QLabel(Dialog)
        self.icon_image.setGeometry(QtCore.QRect(420, 210, 61, 51))
        self.icon_image.setText("")
        self.icon_image.setObjectName("icon_image")
        self.remove_icon_push_btn = QtWidgets.QPushButton(Dialog)
        self.remove_icon_push_btn.setGeometry(QtCore.QRect(330, 210, 75, 23))
        self.remove_icon_push_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.remove_icon_push_btn.setObjectName("remove_icon_push_btn")
        self.status_text_box = QtWidgets.QTextEdit(Dialog)
        self.status_text_box.setGeometry(QtCore.QRect(10, 730, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.status_text_box.setFont(font)
        self.status_text_box.setStyleSheet("QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color: #323232;\n"
"    color: #ffffff;\n"
"    border: 1px solid #404040;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    selection-background-color: #264f78;\n"
"}")
        self.status_text_box.setReadOnly(True)
        self.status_text_box.setObjectName("status_text_box")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setGeometry(QtCore.QRect(530, 790, 132, 41))
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    min-width: 90px;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.generate_code_template_btn = QtWidgets.QPushButton(Dialog)
        self.generate_code_template_btn.setGeometry(QtCore.QRect(670, 790, 221, 41))
        self.generate_code_template_btn.setStyleSheet("QPushButton {\n"
"                background-color: #2E8B57;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 4px;\n"
"                font-family: Calibri;\n"
"                font-size: 13pt;   \n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #3CB371;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #228B22;\n"
"            }\n"
"")
        self.generate_code_template_btn.setObjectName("generate_code_template_btn")
        self.selected_exporter_label = QtWidgets.QLabel(Dialog)
        self.selected_exporter_label.setGeometry(QtCore.QRect(660, 740, 121, 16))
        self.selected_exporter_label.setObjectName("selected_exporter_label")
        self.addition_type_combo_box_2 = QtWidgets.QComboBox(Dialog)
        self.addition_type_combo_box_2.setGeometry(QtCore.QRect(660, 760, 231, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addition_type_combo_box_2.setFont(font)
        self.addition_type_combo_box_2.setStyleSheet("QDialog {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"    border: 1px solid #404040;\n"
"    border-radius: 6px;\n"
"}")
        self.addition_type_combo_box_2.setObjectName("addition_type_combo_box_2")
        self.addition_type_combo_box_2.addItem("")
        self.addition_type_combo_box_2.addItem("")
        self.addition_type_combo_box_2.addItem("")
        self.open_vs_btn = QtWidgets.QPushButton(Dialog)
        self.open_vs_btn.setGeometry(QtCore.QRect(570, 730, 45, 45))
        self.open_vs_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../resources/visual-studio-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_vs_btn.setIcon(icon)
        self.open_vs_btn.setIconSize(QtCore.QSize(30, 30))
        self.open_vs_btn.setObjectName("open_vs_btn")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 720, 851, 1))
        self.line_2.setStyleSheet("QFrame[frameShape=\"4\"] {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop:0 #2b2b2b,\n"
"                            stop:0.5 #404040,\n"
"                            stop:1 #2b2b2b);\n"
"    border: none;\n"
"    max-height: 2px;\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(150, 460, 851, 1))
        self.line_3.setStyleSheet("QFrame[frameShape=\"4\"] {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop:0 #2b2b2b,\n"
"                            stop:0.5 #404040,\n"
"                            stop:1 #2b2b2b);\n"
"    border: none;\n"
"    max-height: 2 px;\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(550, 10, 2, 431))
        self.line.setStyleSheet("QFrame[frameShape=\"5\"] {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #333333,\n"
"        stop: 0.5 #404040,\n"
"        stop: 1 #333333\n"
"    );\n"
"    border: none;\n"
"    min-width: 2px;\n"
"    max-width: 2px;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.move_tuning_param_up_btn = QtWidgets.QPushButton(Dialog)
        self.move_tuning_param_up_btn.setEnabled(False)
        self.move_tuning_param_up_btn.setGeometry(QtCore.QRect(530, 560, 41, 23))
        self.move_tuning_param_up_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.move_tuning_param_up_btn.setObjectName("move_tuning_param_up_btn")
        self.move_tuning_param_down_btn = QtWidgets.QPushButton(Dialog)
        self.move_tuning_param_down_btn.setEnabled(False)
        self.move_tuning_param_down_btn.setGeometry(QtCore.QRect(530, 600, 41, 23))
        self.move_tuning_param_down_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    border: none;           /* Removed border completely */\n"
"    border-radius: 4px;\n"
"    min-width: 10px;\n"
"    font-family: \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a4a;  /* Simple color change on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d2d;\n"
"    color: #808080;\n"
"}")
        self.move_tuning_param_down_btn.setObjectName("move_tuning_param_down_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_ao_btn.setText(_translate("Dialog", "+"))
        self.remove_ao_btn.setText(_translate("Dialog", "-"))
        self.name_label.setText(_translate("Dialog", "Name:"))
        self.description_label.setText(_translate("Dialog", "Description:"))
        self.display_name_label.setText(_translate("Dialog", "Display name:"))
        self.is_float_point_label.setText(_translate("Dialog", "Is float point:"))
        self.addition_type_label.setText(_translate("Dialog", "Type:"))
        self.collapsible_label.setText(_translate("Dialog", "Collapsible:"))
        self.tuning_parameters_label.setText(_translate("Dialog", "Tuning parameters:"))
        self.supported_platforms_label.setText(_translate("Dialog", "Platforms supported:"))
        self.add_tuning_param_btn.setText(_translate("Dialog", "+"))
        self.remove_tuning_param_btn.setText(_translate("Dialog", "-"))
        self.icon_label.setText(_translate("Dialog", "Icon:"))
        self.icon_push_btn.setText(_translate("Dialog", "Select"))
        self.is_popup_allowed_label.setText(_translate("Dialog", "Is popup allowed:"))
        self.num_input_sockets_label.setText(_translate("Dialog", "Num of inputs:"))
        self.num_output_sockets_label.setText(_translate("Dialog", "Num of outputs:"))
        self.num_inctrl_sockets_label.setText(_translate("Dialog", "Num of in controls:"))
        self.num_outctrl_sockets_label.setText(_translate("Dialog", "Num of out controls:"))
        self.remove_icon_push_btn.setText(_translate("Dialog", "Remove Icon"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.generate_code_template_btn.setText(_translate("Dialog", "Generate Code Template"))
        self.selected_exporter_label.setText(_translate("Dialog", "Selected exporter"))
        self.addition_type_combo_box_2.setItemText(0, _translate("Dialog", "Visual Studio"))
        self.addition_type_combo_box_2.setItemText(1, _translate("Dialog", "Xtensa HiFi DSP"))
        self.addition_type_combo_box_2.setItemText(2, _translate("Dialog", "Cortex-M"))
        self.move_tuning_param_up_btn.setText(_translate("Dialog", "↑"))
        self.move_tuning_param_down_btn.setText(_translate("Dialog", "↓"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
