# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_remote_control_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_remote_control_selection(object):
    def setupUi(self, dialog_remote_control_selection):
        dialog_remote_control_selection.setObjectName("dialog_remote_control_selection")
        dialog_remote_control_selection.setEnabled(True)
        dialog_remote_control_selection.resize(420, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_remote_control_selection.sizePolicy().hasHeightForWidth())
        dialog_remote_control_selection.setSizePolicy(sizePolicy)
        dialog_remote_control_selection.setMinimumSize(QtCore.QSize(420, 240))
        dialog_remote_control_selection.setMaximumSize(QtCore.QSize(420, 240))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        dialog_remote_control_selection.setFont(font)
        dialog_remote_control_selection.setSizeGripEnabled(False)
        dialog_remote_control_selection.setModal(False)
        self.Group0_Profile = QtWidgets.QGroupBox(dialog_remote_control_selection)
        self.Group0_Profile.setGeometry(QtCore.QRect(30, 10, 351, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group0_Profile.sizePolicy().hasHeightForWidth())
        self.Group0_Profile.setSizePolicy(sizePolicy)
        self.Group0_Profile.setMinimumSize(QtCore.QSize(0, 0))
        self.Group0_Profile.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group0_Profile.setFont(font)
        self.Group0_Profile.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group0_Profile.setFlat(True)
        self.Group0_Profile.setCheckable(False)
        self.Group0_Profile.setObjectName("Group0_Profile")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Group0_Profile)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 351, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.hBoxLayout_Profile_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.hBoxLayout_Profile_3.setContentsMargins(10, 10, 10, 10)
        self.hBoxLayout_Profile_3.setSpacing(10)
        self.hBoxLayout_Profile_3.setObjectName("hBoxLayout_Profile_3")
        self.upload = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setMinimumSize(QtCore.QSize(0, 0))
        self.upload.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.upload.setFont(font)
        self.upload.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.upload.setObjectName("upload")
        self.hBoxLayout_Profile_3.addWidget(self.upload)
        self.only = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.only.sizePolicy().hasHeightForWidth())
        self.only.setSizePolicy(sizePolicy)
        self.only.setMinimumSize(QtCore.QSize(0, 0))
        self.only.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.only.setFont(font)
        self.only.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.only.setObjectName("only")
        self.hBoxLayout_Profile_3.addWidget(self.only)
        self.upload_bar = QtWidgets.QProgressBar(dialog_remote_control_selection)
        self.upload_bar.setGeometry(QtCore.QRect(110, 210, 271, 16))
        self.upload_bar.setProperty("value", 0)
        self.upload_bar.setObjectName("upload_bar")
        self.verify_bar = QtWidgets.QProgressBar(dialog_remote_control_selection)
        self.verify_bar.setGeometry(QtCore.QRect(110, 180, 271, 16))
        self.verify_bar.setProperty("value", 0)
        self.verify_bar.setObjectName("verify_bar")
        self.label = QtWidgets.QLabel(dialog_remote_control_selection)
        self.label.setGeometry(QtCore.QRect(50, 180, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog_remote_control_selection)
        self.label_2.setGeometry(QtCore.QRect(40, 210, 54, 12))
        self.label_2.setObjectName("label_2")
        self.save = QtWidgets.QPushButton(dialog_remote_control_selection)
        self.save.setGeometry(QtCore.QRect(40, 100, 331, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save.sizePolicy().hasHeightForWidth())
        self.save.setSizePolicy(sizePolicy)
        self.save.setMinimumSize(QtCore.QSize(0, 0))
        self.save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.save.setFont(font)
        self.save.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.save.setObjectName("save")
        self.label_3 = QtWidgets.QLabel(dialog_remote_control_selection)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 71, 16))
        self.label_3.setObjectName("label_3")
        self.convert_bar = QtWidgets.QProgressBar(dialog_remote_control_selection)
        self.convert_bar.setGeometry(QtCore.QRect(110, 150, 271, 16))
        self.convert_bar.setProperty("value", 0)
        self.convert_bar.setObjectName("convert_bar")

        self.retranslateUi(dialog_remote_control_selection)
        QtCore.QMetaObject.connectSlotsByName(dialog_remote_control_selection)

    def retranslateUi(self, dialog_remote_control_selection):
        _translate = QtCore.QCoreApplication.translate
        dialog_remote_control_selection.setWindowTitle(_translate("dialog_remote_control_selection", "Options"))
        self.Group0_Profile.setTitle(_translate("dialog_remote_control_selection", "Connect Select"))
        self.upload.setText(_translate("dialog_remote_control_selection", "Upload Design to Target"))
        self.only.setText(_translate("dialog_remote_control_selection", "Connect Only"))
        self.label.setText(_translate("dialog_remote_control_selection", "verify： "))
        self.label_2.setText(_translate("dialog_remote_control_selection", "upload："))
        self.save.setText(_translate("dialog_remote_control_selection", "Save"))
        self.label_3.setText(_translate("dialog_remote_control_selection", "convert："))
