# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_command.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_export_command(object):
    def setupUi(self, export_command):
        export_command.setObjectName("export_command")
        export_command.resize(440, 450)
        export_command.setMinimumSize(QtCore.QSize(440, 450))
        export_command.setMaximumSize(QtCore.QSize(440, 450))
        export_command.setStyleSheet("background-color: #474747;")
        self.textEdit = QtWidgets.QTextEdit(export_command)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 400, 300))
        self.textEdit.setStyleSheet("border: 2px solid rgb(161,161,161);\n"
"color:white;\n"
"font: 12pt \"Calibri\";")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(export_command)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 18))
        self.label.setStyleSheet("font: 12pt \"Calibri\";\n"
"color:white;")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(export_command)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 350, 381, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(10, 7, 10, 7)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate.sizePolicy().hasHeightForWidth())
        self.generate.setSizePolicy(sizePolicy)
        self.generate.setFocusPolicy(QtCore.Qt.NoFocus)
        self.generate.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border-color: darkGray;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"    padding: 2px;\n"
"    background-color: lightGray;\n"
"    font: 14pt \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkGray;\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: darkGray;\n"
"}")
        self.generate.setObjectName("generate")
        self.horizontalLayout.addWidget(self.generate)
        self.Copy = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Copy.sizePolicy().hasHeightForWidth())
        self.Copy.setSizePolicy(sizePolicy)
        self.Copy.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Copy.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border-color: darkGray;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"    padding: 2px;\n"
"    background-color: lightGray;\n"
"    font: 14pt \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkGray;\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: darkGray;\n"
"}")
        self.Copy.setObjectName("Copy")
        self.horizontalLayout.addWidget(self.Copy)
        self.Close = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Close.sizePolicy().hasHeightForWidth())
        self.Close.setSizePolicy(sizePolicy)
        self.Close.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border-color: darkGray;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"    padding: 2px;\n"
"    background-color: lightGray;\n"
"    font: 14pt \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkGray;\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color: darkGray;\n"
"}")
        self.Close.setObjectName("Close")
        self.horizontalLayout.addWidget(self.Close)
        self.progressBar = QtWidgets.QProgressBar(export_command)
        self.progressBar.setGeometry(QtCore.QRect(70, 410, 301, 21))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(export_command)
        QtCore.QMetaObject.connectSlotsByName(export_command)

    def retranslateUi(self, export_command):
        _translate = QtCore.QCoreApplication.translate
        export_command.setWindowTitle(_translate("export_command", "Dialog"))
        self.label.setText(_translate("export_command", "Information: "))
        self.generate.setText(_translate("export_command", "Generate"))
        self.Copy.setText(_translate("export_command", "Copy"))
        self.Close.setText(_translate("export_command", "Close"))
