# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flow_ai_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from flowstudio.functions.special_components import textEdit_enter


class Ui_flow_ai_dialog(object):
    def setupUi(self, flow_ai_dialog):
        flow_ai_dialog.setObjectName("flow_ai_dialog")
        flow_ai_dialog.resize(550, 842)
        flow_ai_dialog.setMinimumSize(QtCore.QSize(550, 0))
        flow_ai_dialog.setMaximumSize(QtCore.QSize(1000, 2000))
        flow_ai_dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        flow_ai_dialog.setStyleSheet("background-color: rgba(0, 0, 0, 0.2);")
        self.top_bar_widget = QtWidgets.QWidget(flow_ai_dialog)
        self.top_bar_widget.setGeometry(QtCore.QRect(0, 0, 550, 41))
        self.top_bar_widget.setMinimumSize(QtCore.QSize(550, 0))
        self.top_bar_widget.setMaximumSize(QtCore.QSize(550, 16777215))
        self.top_bar_widget.setStyleSheet("background-color: #2a0d4b;")
        self.top_bar_widget.setObjectName("top_bar_widget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.top_bar_widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 551, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.top_bar_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.top_bar_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.top_bar_layout.setContentsMargins(10, 0, 10, 0)
        self.top_bar_layout.setSpacing(100)
        self.top_bar_layout.setObjectName("top_bar_layout")
        self.history = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history.setStyleSheet("border: none;\n"
"text-align: left;\n"
"                                ")
        self.history.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/history.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history.setIcon(icon)
        self.history.setIconSize(QtCore.QSize(24, 24))
        self.history.setObjectName("history")
        self.top_bar_layout.addWidget(self.history)
        self.mode_layout = QtWidgets.QHBoxLayout()
        self.mode_layout.setSpacing(5)
        self.mode_layout.setObjectName("mode_layout")
        self.mode_icon = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.mode_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mode_icon.setStyleSheet("border: none;\n"
"                                                ")
        self.mode_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mode_icon.setIcon(icon1)
        self.mode_icon.setIconSize(QtCore.QSize(24, 24))
        self.mode_icon.setObjectName("mode_icon")
        self.mode_layout.addWidget(self.mode_icon)
        self.mode_label = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.mode_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mode_label.setStyleSheet("border: none;\n"
"                                                    color: white;\n"
"                                                    font-size: 18px;\n"
"                                                    font-family: Calibri;\n"
"                                                    font-weight: bold;\n"
"                                                ")
        self.mode_label.setIconSize(QtCore.QSize(24, 24))
        self.mode_label.setObjectName("mode_label")
        self.mode_layout.addWidget(self.mode_label)
        self.mode_down = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.mode_down.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mode_down.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mode_down.setStyleSheet("border: none;\n"
"                                                    margin-left: -2px;\n"
"                                                ")
        self.mode_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../resources/mode-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mode_down.setIcon(icon2)
        self.mode_down.setIconSize(QtCore.QSize(20, 20))
        self.mode_down.setObjectName("mode_down")
        self.mode_layout.addWidget(self.mode_down)
        self.top_bar_layout.addLayout(self.mode_layout)
        self.new_project = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.new_project.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_project.setStyleSheet("border: none;\n"
"text-align: right;\n"
"                                ")
        self.new_project.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_project.setIcon(icon3)
        self.new_project.setIconSize(QtCore.QSize(24, 24))
        self.new_project.setObjectName("new_project")
        self.top_bar_layout.addWidget(self.new_project)
        self.top_bar_layout.setStretch(0, 1)
        self.top_bar_layout.setStretch(2, 1)
        self.new_project.raise_()
        self.history.raise_()
        self.mode_list_widget = QtWidgets.QWidget(flow_ai_dialog)
        self.mode_list_widget.setGeometry(QtCore.QRect(130, 40, 290, 80))
        self.mode_list_widget.setStyleSheet("background-color: #474747;\n"
"                    border-radius: 15px;\n"
"                ")
        self.mode_list_widget.setObjectName("mode_list_widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.mode_list_widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 271, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mode_list_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mode_list_layout.setContentsMargins(0, 0, 0, 0)
        self.mode_list_layout.setSpacing(5)
        self.mode_list_layout.setObjectName("mode_list_layout")
        self.mode_chat_layout = QtWidgets.QHBoxLayout()
        self.mode_chat_layout.setContentsMargins(-1, -1, 22, -1)
        self.mode_chat_layout.setSpacing(2)
        self.mode_chat_layout.setObjectName("mode_chat_layout")
        self.chat_icon = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chat_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chat_icon.setStyleSheet("border: none;\n"
"                                        ")
        self.chat_icon.setText("")
        self.chat_icon.setIcon(icon1)
        self.chat_icon.setIconSize(QtCore.QSize(24, 24))
        self.chat_icon.setObjectName("chat_icon")
        self.mode_chat_layout.addWidget(self.chat_icon)
        self.chat_label = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chat_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chat_label.setStyleSheet("border: none;\n"
"                                            color: white;\n"
"                                            font-size: 14px;\n"
"                                            font-family: Calibri;\n"
"                                        ")
        self.chat_label.setIconSize(QtCore.QSize(0, 0))
        self.chat_label.setObjectName("chat_label")
        self.mode_chat_layout.addWidget(self.chat_label)
        self.chat_des = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chat_des.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chat_des.setStyleSheet("border: none;\n"
"                                            font: italic 9pt \"Calibri\";\n"
"                                            color: #7e7e7e;\n"
"                                        ")
        self.chat_des.setIconSize(QtCore.QSize(24, 24))
        self.chat_des.setObjectName("chat_des")
        self.mode_chat_layout.addWidget(self.chat_des)
        self.chat_tick = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chat_tick.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chat_tick.setStyleSheet("border: none;\n"
"                                        ")
        self.chat_tick.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../resources/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_tick.setIcon(icon4)
        self.chat_tick.setIconSize(QtCore.QSize(22, 22))
        self.chat_tick.setObjectName("chat_tick")
        self.mode_chat_layout.addWidget(self.chat_tick)
        self.mode_list_layout.addLayout(self.mode_chat_layout)
        self.mode_design_layout = QtWidgets.QHBoxLayout()
        self.mode_design_layout.setSpacing(2)
        self.mode_design_layout.setObjectName("mode_design_layout")
        self.design_icon = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.design_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.design_icon.setStyleSheet("border: none;\n"
"                                        ")
        self.design_icon.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../resources/design.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.design_icon.setIcon(icon5)
        self.design_icon.setIconSize(QtCore.QSize(24, 24))
        self.design_icon.setObjectName("design_icon")
        self.mode_design_layout.addWidget(self.design_icon)
        self.design_label = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.design_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.design_label.setStyleSheet("border: none;\n"
"                                            color: white;\n"
"                                            font-size: 14px;\n"
"                                            font-family: Calibri;\n"
"                                        ")
        self.design_label.setIconSize(QtCore.QSize(0, 0))
        self.design_label.setObjectName("design_label")
        self.mode_design_layout.addWidget(self.design_label)
        self.design_des = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.design_des.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.design_des.setStyleSheet("border: none;\n"
"                                            font: italic 9pt \"Calibri\";\n"
"                                            color: #7e7e7e;\n"
"                                        ")
        self.design_des.setIconSize(QtCore.QSize(24, 24))
        self.design_des.setObjectName("design_des")
        self.mode_design_layout.addWidget(self.design_des)
        self.design_tick = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.design_tick.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.design_tick.setStyleSheet("border: none;\n"
"                                        ")
        self.design_tick.setText("")
        self.design_tick.setIcon(icon4)
        self.design_tick.setIconSize(QtCore.QSize(22, 22))
        self.design_tick.setObjectName("design_tick")
        self.mode_design_layout.addWidget(self.design_tick)
        self.mode_list_layout.addLayout(self.mode_design_layout)
        self.tab_widget = QtWidgets.QTabWidget(flow_ai_dialog)
        self.tab_widget.setGeometry(QtCore.QRect(0, 40, 550, 641))
        self.tab_widget.setMinimumSize(QtCore.QSize(550, 0))
        self.tab_widget.setMaximumSize(QtCore.QSize(550, 16777215))
        self.tab_widget.setStyleSheet("QTabWidget::pane {border: none;}\n"
"QTabWidget QWidget{background: transparent;}")
        self.tab_widget.setObjectName("tab_widget")
        self.chat_tab = QtWidgets.QWidget()
        self.chat_tab.setStyleSheet("")
        self.chat_tab.setObjectName("chat_tab")
        self.chat_panel = QtWidgets.QScrollArea(self.chat_tab)
        self.chat_panel.setGeometry(QtCore.QRect(0, 10, 550, 371))
        self.chat_panel.setMinimumSize(QtCore.QSize(550, 0))
        self.chat_panel.setMaximumSize(QtCore.QSize(550, 16777215))
        self.chat_panel.setStyleSheet("QScrollBar:vertical {\n"
"    border-width: 0px;\n"
"    border: none;\n"
"    background:rgba(64, 65, 79, 0);\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f, stop:1 #4f4f4f);\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"    margin: 0 0 0 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f,  stop:1 #4f4f4f);\n"
"    height: 0px;\n"
"    border: none;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;    \n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));\n"
"    height: 0 px;\n"
"    border: none;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"")
        self.chat_panel.setWidgetResizable(True)
        self.chat_panel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.chat_panel.setObjectName("chat_panel")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 548, 369))
        self.scrollAreaWidgetContents.setStyleSheet("font: 12pt \"Calibri\";")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 531, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.chat_panel_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.chat_panel_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.chat_panel_verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.chat_panel_verticalLayout.setSpacing(10)
        self.chat_panel_verticalLayout.setObjectName("chat_panel_verticalLayout")
        self.example_horizontalLayout = QtWidgets.QHBoxLayout()
        self.example_horizontalLayout.setObjectName("example_horizontalLayout")
        self.example_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.example_1.sizePolicy().hasHeightForWidth())
        self.example_1.setSizePolicy(sizePolicy)
        self.example_1.setMinimumSize(QtCore.QSize(150, 100))
        self.example_1.setMaximumSize(QtCore.QSize(150, 100))
        self.example_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.example_1.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font: 12pt \"Calibri\";\n"
"border: 2px solid #7f7f7f;\n"
"border-radius: 20px;\n"
"padding: 10px;\n"
"text-align: center;")
        self.example_1.setObjectName("example_1")
        self.example_horizontalLayout.addWidget(self.example_1)
        self.example_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.example_2.sizePolicy().hasHeightForWidth())
        self.example_2.setSizePolicy(sizePolicy)
        self.example_2.setMinimumSize(QtCore.QSize(150, 100))
        self.example_2.setMaximumSize(QtCore.QSize(150, 100))
        self.example_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.example_2.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font: 12pt \"Calibri\";\n"
"border: 2px solid #7f7f7f;\n"
"border-radius: 20px;\n"
"padding: 10px;\n"
"text-align: center;")
        self.example_2.setObjectName("example_2")
        self.example_horizontalLayout.addWidget(self.example_2)
        self.chat_panel_verticalLayout.addLayout(self.example_horizontalLayout)
        self.more_example_horizontalLayout = QtWidgets.QHBoxLayout()
        self.more_example_horizontalLayout.setObjectName("more_example_horizontalLayout")
        self.example_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.example_4.sizePolicy().hasHeightForWidth())
        self.example_4.setSizePolicy(sizePolicy)
        self.example_4.setMinimumSize(QtCore.QSize(150, 100))
        self.example_4.setMaximumSize(QtCore.QSize(150, 100))
        self.example_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.example_4.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font: 12pt \"Calibri\";\n"
"border: 2px solid #7f7f7f;\n"
"border-radius: 20px;\n"
"padding: 10px;\n"
"text-align: center;")
        self.example_4.setObjectName("example_4")
        self.more_example_horizontalLayout.addWidget(self.example_4)
        self.example_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.example_3.sizePolicy().hasHeightForWidth())
        self.example_3.setSizePolicy(sizePolicy)
        self.example_3.setMinimumSize(QtCore.QSize(150, 100))
        self.example_3.setMaximumSize(QtCore.QSize(150, 100))
        self.example_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.example_3.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font: 12pt \"Calibri\";\n"
"border: 2px solid #7f7f7f;\n"
"border-radius: 20px;\n"
"padding: 10px;\n"
"text-align: center;")
        self.example_3.setObjectName("example_3")
        self.more_example_horizontalLayout.addWidget(self.example_3)
        self.chat_panel_verticalLayout.addLayout(self.more_example_horizontalLayout)
        self.chat_panel.setWidget(self.scrollAreaWidgetContents)
        self.input_edit_widget = QtWidgets.QWidget(self.chat_tab)
        self.input_edit_widget.setGeometry(QtCore.QRect(60, 390, 430, 50))
        self.input_edit_widget.setMinimumSize(QtCore.QSize(430, 50))
        self.input_edit_widget.setMaximumSize(QtCore.QSize(1000, 500))
        self.input_edit_widget.setStyleSheet("#input_edit_widget{\n"
"background-color: #181717;\n"
"border-radius: 25px;\n"
"border: 2px solid #7f7f7f;\n"
"bottom: 0px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.input_edit_widget.setObjectName("input_edit_widget")
        self.send = QtWidgets.QPushButton(self.input_edit_widget)
        self.send.setGeometry(QtCore.QRect(360, 5, 50, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send.sizePolicy().hasHeightForWidth())
        self.send.setSizePolicy(sizePolicy)
        self.send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send.setStyleSheet("background-color: #181717;\n"
"border: none")
        self.send.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../resources/ai-chat-send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("../resources/ai-chat-send-disable.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.send.setIcon(icon6)
        self.send.setIconSize(QtCore.QSize(35, 35))
        self.send.setObjectName("send")
        self.stop = QtWidgets.QPushButton(self.input_edit_widget)
        self.stop.setGeometry(QtCore.QRect(360, 5, 50, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop.setStyleSheet("background-color: #181717;\n"
"border: none")
        self.stop.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../resources/ai-chat-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon7)
        self.stop.setIconSize(QtCore.QSize(32, 32))
        self.stop.setObjectName("stop")
        self.user_input_box = textEdit_enter(self.input_edit_widget)
        self.user_input_box.setGeometry(QtCore.QRect(20, 10, 320, 30))
        self.user_input_box.setMinimumSize(QtCore.QSize(0, 30))
        self.user_input_box.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"    font: 12pt \"Calibri\";\n"
"    background-color: #181717;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border-width: 0px;\n"
"    border: none;\n"
"    background: #181717;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f, stop:1 #4f4f4f);\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"    margin: 0 0 0 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f,  stop:1 #4f4f4f);\n"
"    height: 0px;\n"
"    border: none;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;    \n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));\n"
"    height: 0 px;\n"
"    border: none;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"")
        self.user_input_box.setObjectName("user_input_box")
        self.user_input_box.raise_()
        self.stop.raise_()
        self.send.raise_()
        self.design_label_2 = QtWidgets.QPushButton(self.chat_tab)
        self.design_label_2.setGeometry(QtCore.QRect(90, 440, 371, 20))
        self.design_label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.design_label_2.setStyleSheet("border: none;\n"
"                                            color: white;\n"
"                                            font-size: 14px;\n"
"                                            font-family: Calibri;\n"
"                                        ")
        self.design_label_2.setIconSize(QtCore.QSize(0, 0))
        self.design_label_2.setObjectName("design_label_2")
        self.tab_widget.addTab(self.chat_tab, "")
        self.design = QtWidgets.QWidget()
        self.design.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.design.setObjectName("design")
        self.design_panel = QtWidgets.QScrollArea(self.design)
        self.design_panel.setGeometry(QtCore.QRect(0, 10, 550, 581))
        self.design_panel.setStyleSheet("QScrollBar:vertical {\n"
"    border-width: 0px;\n"
"    border: none;\n"
"    background:rgba(64, 65, 79, 0);\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f, stop:1 #4f4f4f);\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"    margin: 0 0 0 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f,  stop:1 #4f4f4f);\n"
"    height: 0px;\n"
"    border: none;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;    \n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));\n"
"    height: 0 px;\n"
"    border: none;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"")
        self.design_panel.setWidgetResizable(True)
        self.design_panel.setObjectName("design_panel")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 548, 579))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 531, 643))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.design_tab_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.design_tab_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.design_tab_verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.design_tab_verticalLayout.setSpacing(10)
        self.design_tab_verticalLayout.setObjectName("design_tab_verticalLayout")
        self.form_factor = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_factor.sizePolicy().hasHeightForWidth())
        self.form_factor.setSizePolicy(sizePolicy)
        self.form_factor.setMinimumSize(QtCore.QSize(100, 0))
        self.form_factor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.form_factor.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";")
        self.form_factor.setObjectName("form_factor")
        self.design_tab_verticalLayout.addWidget(self.form_factor)
        self.form_factor_horizontalLayout = QtWidgets.QHBoxLayout()
        self.form_factor_horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.form_factor_horizontalLayout.setSpacing(10)
        self.form_factor_horizontalLayout.setObjectName("form_factor_horizontalLayout")
        self.headset_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headset_button.sizePolicy().hasHeightForWidth())
        self.headset_button.setSizePolicy(sizePolicy)
        self.headset_button.setMinimumSize(QtCore.QSize(70, 60))
        self.headset_button.setMaximumSize(QtCore.QSize(70, 60))
        self.headset_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.headset_button.setStyleSheet("border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.headset_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../resources/headset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.headset_button.setIcon(icon8)
        self.headset_button.setIconSize(QtCore.QSize(40, 40))
        self.headset_button.setObjectName("headset_button")
        self.form_factor_horizontalLayout.addWidget(self.headset_button)
        self.speaker_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_button.sizePolicy().hasHeightForWidth())
        self.speaker_button.setSizePolicy(sizePolicy)
        self.speaker_button.setMinimumSize(QtCore.QSize(70, 60))
        self.speaker_button.setMaximumSize(QtCore.QSize(70, 60))
        self.speaker_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speaker_button.setStyleSheet("border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.speaker_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../resources/speaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speaker_button.setIcon(icon9)
        self.speaker_button.setIconSize(QtCore.QSize(36, 36))
        self.speaker_button.setObjectName("speaker_button")
        self.form_factor_horizontalLayout.addWidget(self.speaker_button)
        self.pc_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pc_button.sizePolicy().hasHeightForWidth())
        self.pc_button.setSizePolicy(sizePolicy)
        self.pc_button.setMinimumSize(QtCore.QSize(70, 60))
        self.pc_button.setMaximumSize(QtCore.QSize(70, 60))
        self.pc_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pc_button.setStyleSheet("border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.pc_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../resources/pc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pc_button.setIcon(icon10)
        self.pc_button.setIconSize(QtCore.QSize(36, 36))
        self.pc_button.setObjectName("pc_button")
        self.form_factor_horizontalLayout.addWidget(self.pc_button)
        self.mic_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mic_button.sizePolicy().hasHeightForWidth())
        self.mic_button.setSizePolicy(sizePolicy)
        self.mic_button.setMinimumSize(QtCore.QSize(70, 60))
        self.mic_button.setMaximumSize(QtCore.QSize(70, 60))
        self.mic_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mic_button.setStyleSheet("border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.mic_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../resources/mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mic_button.setIcon(icon11)
        self.mic_button.setIconSize(QtCore.QSize(40, 40))
        self.mic_button.setObjectName("mic_button")
        self.form_factor_horizontalLayout.addWidget(self.mic_button)
        self.design_tab_verticalLayout.addLayout(self.form_factor_horizontalLayout)
        self.signal_path = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signal_path.sizePolicy().hasHeightForWidth())
        self.signal_path.setSizePolicy(sizePolicy)
        self.signal_path.setMinimumSize(QtCore.QSize(100, 0))
        self.signal_path.setMaximumSize(QtCore.QSize(100, 16777215))
        self.signal_path.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";")
        self.signal_path.setObjectName("signal_path")
        self.design_tab_verticalLayout.addWidget(self.signal_path)
        self.signal_path_horizontalLayout = QtWidgets.QHBoxLayout()
        self.signal_path_horizontalLayout.setObjectName("signal_path_horizontalLayout")
        self.playback_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playback_btn.sizePolicy().hasHeightForWidth())
        self.playback_btn.setSizePolicy(sizePolicy)
        self.playback_btn.setMinimumSize(QtCore.QSize(150, 60))
        self.playback_btn.setMaximumSize(QtCore.QSize(150, 60))
        self.playback_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playback_btn.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";\n"
"border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.playback_btn.setObjectName("playback_btn")
        self.signal_path_horizontalLayout.addWidget(self.playback_btn)
        self.recording_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recording_btn.sizePolicy().hasHeightForWidth())
        self.recording_btn.setSizePolicy(sizePolicy)
        self.recording_btn.setMinimumSize(QtCore.QSize(150, 60))
        self.recording_btn.setMaximumSize(QtCore.QSize(150, 60))
        self.recording_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recording_btn.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";\n"
"border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.recording_btn.setObjectName("recording_btn")
        self.signal_path_horizontalLayout.addWidget(self.recording_btn)
        self.design_tab_verticalLayout.addLayout(self.signal_path_horizontalLayout)
        self.complexity = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.complexity.sizePolicy().hasHeightForWidth())
        self.complexity.setSizePolicy(sizePolicy)
        self.complexity.setMinimumSize(QtCore.QSize(100, 0))
        self.complexity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.complexity.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";")
        self.complexity.setObjectName("complexity")
        self.design_tab_verticalLayout.addWidget(self.complexity)
        self.complexity_horizontalLayout = QtWidgets.QHBoxLayout()
        self.complexity_horizontalLayout.setObjectName("complexity_horizontalLayout")
        self.basic_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basic_btn.sizePolicy().hasHeightForWidth())
        self.basic_btn.setSizePolicy(sizePolicy)
        self.basic_btn.setMinimumSize(QtCore.QSize(150, 60))
        self.basic_btn.setMaximumSize(QtCore.QSize(150, 60))
        self.basic_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.basic_btn.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";\n"
"border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.basic_btn.setObjectName("basic_btn")
        self.complexity_horizontalLayout.addWidget(self.basic_btn)
        self.advanced_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_btn.sizePolicy().hasHeightForWidth())
        self.advanced_btn.setSizePolicy(sizePolicy)
        self.advanced_btn.setMinimumSize(QtCore.QSize(150, 60))
        self.advanced_btn.setMaximumSize(QtCore.QSize(150, 60))
        self.advanced_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.advanced_btn.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";\n"
"border: 2px solid #a8a8a8;\n"
"border-radius: 12px;")
        self.advanced_btn.setObjectName("advanced_btn")
        self.complexity_horizontalLayout.addWidget(self.advanced_btn)
        self.design_tab_verticalLayout.addLayout(self.complexity_horizontalLayout)
        self.design_for = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.design_for.sizePolicy().hasHeightForWidth())
        self.design_for.setSizePolicy(sizePolicy)
        self.design_for.setMinimumSize(QtCore.QSize(100, 0))
        self.design_for.setMaximumSize(QtCore.QSize(100, 16777215))
        self.design_for.setStyleSheet("color: white;\n"
"font: 14pt \"Calibri\";")
        self.design_for.setObjectName("design_for")
        self.design_tab_verticalLayout.addWidget(self.design_for)
        self.fine_tune_horizontalLayout = QtWidgets.QHBoxLayout()
        self.fine_tune_horizontalLayout.setObjectName("fine_tune_horizontalLayout")
        self.fine_tune_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fine_tune_label.sizePolicy().hasHeightForWidth())
        self.fine_tune_label.setSizePolicy(sizePolicy)
        self.fine_tune_label.setMinimumSize(QtCore.QSize(100, 0))
        self.fine_tune_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.fine_tune_label.setStyleSheet("color: white;\n"
"font: 13pt \"Calibri\";")
        self.fine_tune_label.setObjectName("fine_tune_label")
        self.fine_tune_horizontalLayout.addWidget(self.fine_tune_label)
        self.design_tab_verticalLayout.addLayout(self.fine_tune_horizontalLayout)
        self.design_for_horizontalLayout = QtWidgets.QHBoxLayout()
        self.design_for_horizontalLayout.setSpacing(0)
        self.design_for_horizontalLayout.setObjectName("design_for_horizontalLayout")
        self.describe_widget = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.describe_widget.sizePolicy().hasHeightForWidth())
        self.describe_widget.setSizePolicy(sizePolicy)
        self.describe_widget.setMinimumSize(QtCore.QSize(400, 110))
        self.describe_widget.setMaximumSize(QtCore.QSize(400, 110))
        self.describe_widget.setStyleSheet("")
        self.describe_widget.setObjectName("describe_widget")
        self.describe_textEdit = QtWidgets.QTextEdit(self.describe_widget)
        self.describe_textEdit.setGeometry(QtCore.QRect(20, 0, 361, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.describe_textEdit.sizePolicy().hasHeightForWidth())
        self.describe_textEdit.setSizePolicy(sizePolicy)
        self.describe_textEdit.setMinimumSize(QtCore.QSize(0, 110))
        self.describe_textEdit.setMaximumSize(QtCore.QSize(16777215, 110))
        self.describe_textEdit.setStyleSheet("color: white;\n"
"font: 12pt \"Calibri\";\n"
"border: 2px solid #a8a8a8;\n"
"border-radius: 12px;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"padding-top: 2px;")
        self.describe_textEdit.setAcceptRichText(False)
        self.describe_textEdit.setObjectName("describe_textEdit")
        self.count_limit_label = QtWidgets.QLabel(self.describe_widget)
        self.count_limit_label.setGeometry(QtCore.QRect(320, 80, 51, 21))
        self.count_limit_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.count_limit_label.setStyleSheet("color: #808080;\n"
"font: 10pt \"Calibri\";")
        self.count_limit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_limit_label.setObjectName("count_limit_label")
        self.design_for_horizontalLayout.addWidget(self.describe_widget)
        self.design_tab_verticalLayout.addLayout(self.design_for_horizontalLayout)
        self.generate_btn_horizontalLayout = QtWidgets.QHBoxLayout()
        self.generate_btn_horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.generate_btn_horizontalLayout.setSpacing(0)
        self.generate_btn_horizontalLayout.setObjectName("generate_btn_horizontalLayout")
        self.generate_btn_widget = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_btn_widget.sizePolicy().hasHeightForWidth())
        self.generate_btn_widget.setSizePolicy(sizePolicy)
        self.generate_btn_widget.setMinimumSize(QtCore.QSize(400, 60))
        self.generate_btn_widget.setMaximumSize(QtCore.QSize(400, 60))
        self.generate_btn_widget.setStyleSheet("")
        self.generate_btn_widget.setObjectName("generate_btn_widget")
        self.generate_btn = QtWidgets.QPushButton(self.generate_btn_widget)
        self.generate_btn.setGeometry(QtCore.QRect(0, 0, 400, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_btn.sizePolicy().hasHeightForWidth())
        self.generate_btn.setSizePolicy(sizePolicy)
        self.generate_btn.setMinimumSize(QtCore.QSize(400, 60))
        self.generate_btn.setMaximumSize(QtCore.QSize(400, 60))
        self.generate_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate_btn.setStyleSheet("color: white;\n"
"font: 16pt \"Calibri\";\n"
"border: 2px solid #a8a8a8;\n"
"border-radius: 30px;\n"
"background-color: #0094e3;")
        self.generate_btn.setObjectName("generate_btn")
        self.generate_btn_horizontalLayout.addWidget(self.generate_btn_widget)
        self.design_tab_verticalLayout.addLayout(self.generate_btn_horizontalLayout)
        self.generate_res_verticalLayout = QtWidgets.QVBoxLayout()
        self.generate_res_verticalLayout.setContentsMargins(50, -1, 50, -1)
        self.generate_res_verticalLayout.setSpacing(0)
        self.generate_res_verticalLayout.setObjectName("generate_res_verticalLayout")
        self.generate_res_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.generate_res_label.setStyleSheet("color: white;\n"
"font: 12pt \"Calibri\";")
        self.generate_res_label.setText("")
        self.generate_res_label.setAlignment(QtCore.Qt.AlignCenter)
        self.generate_res_label.setWordWrap(True)
        self.generate_res_label.setObjectName("generate_res_label")
        self.generate_res_verticalLayout.addWidget(self.generate_res_label)
        self.loading_horizontalLayout = QtWidgets.QHBoxLayout()
        self.loading_horizontalLayout.setSpacing(12)
        self.loading_horizontalLayout.setObjectName("loading_horizontalLayout")
        self.generate_res_verticalLayout.addLayout(self.loading_horizontalLayout)
        self.design_tab_verticalLayout.addLayout(self.generate_res_verticalLayout)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.widget_2.setObjectName("widget_2")
        self.design_tab_verticalLayout.addWidget(self.widget_2)
        self.design_tab_verticalLayout.setStretch(11, 1)
        self.design_panel.setWidget(self.scrollAreaWidgetContents_3)
        self.tab_widget.addTab(self.design, "")
        self.drag_line = QtWidgets.QLabel(flow_ai_dialog)
        self.drag_line.setGeometry(QtCore.QRect(0, 0, 3, 461))
        self.drag_line.setMinimumSize(QtCore.QSize(3, 0))
        self.drag_line.setMaximumSize(QtCore.QSize(3, 16777215))
        self.drag_line.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.drag_line.setStyleSheet("background-color: rgba(0, 0, 0, 1);")
        self.drag_line.setText("")
        self.drag_line.setObjectName("drag_line")
        self.history_item_scrollArea = QtWidgets.QScrollArea(flow_ai_dialog)
        self.history_item_scrollArea.setGeometry(QtCore.QRect(100, 650, 340, 130))
        self.history_item_scrollArea.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f, stop:1 #4f4f4f);\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"    margin: 0 0 0 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0 #4f4f4f, stop: 0.5 #4f4f4f,  stop:1 #4f4f4f);\n"
"    height: 0px;\n"
"    border: none;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;    \n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));\n"
"    height: 0 px;\n"
"    border: none;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"    background: rgba(64, 65, 79, 0);\n"
"}\n"
"")
        self.history_item_scrollArea.setWidgetResizable(True)
        self.history_item_scrollArea.setObjectName("history_item_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 338, 128))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color: #2a0d4b;\n"
"border: none;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 321, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.history_item_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.history_item_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.history_item_verticalLayout.setSpacing(20)
        self.history_item_verticalLayout.setObjectName("history_item_verticalLayout")
        self.history_item_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.top_bar_widget.raise_()
        self.tab_widget.raise_()
        self.mode_list_widget.raise_()
        self.history_item_scrollArea.raise_()
        self.drag_line.raise_()

        self.retranslateUi(flow_ai_dialog)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(flow_ai_dialog)

    def retranslateUi(self, flow_ai_dialog):
        _translate = QtCore.QCoreApplication.translate
        flow_ai_dialog.setWindowTitle(_translate("flow_ai_dialog", "flow_ai"))
        self.mode_label.setText(_translate("flow_ai_dialog", "Chat"))
        self.chat_label.setText(_translate("flow_ai_dialog", "Chat Mode"))
        self.chat_des.setText(_translate("flow_ai_dialog", "Need help? Just ask!​"))
        self.design_label.setText(_translate("flow_ai_dialog", "Design Mode"))
        self.design_des.setText(_translate("flow_ai_dialog", "Generative signal flow"))
        self.example_1.setText(_translate("flow_ai_dialog", "How to start\n"
" my first Flow\n"
" project?"))
        self.example_2.setText(_translate("flow_ai_dialog", "How to use a\n"
" PEQ Audio\n"
" Object?"))
        self.example_4.setText(_translate("flow_ai_dialog", "How is \n"
" my data \n"
" being used?"))
        self.example_3.setText(_translate("flow_ai_dialog", "What is \n"
" Flow AI Agent?"))
        self.user_input_box.setPlaceholderText(_translate("flow_ai_dialog", "Chat with Flow AI Agent"))
        self.design_label_2.setText(_translate("flow_ai_dialog", "Flow AI Agent can make mistakes. Please verify the responses."))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.chat_tab), _translate("flow_ai_dialog", "Tab 1"))
        self.form_factor.setText(_translate("flow_ai_dialog", "Form Factor​"))
        self.signal_path.setText(_translate("flow_ai_dialog", "Signal Path​"))
        self.playback_btn.setText(_translate("flow_ai_dialog", "Playback"))
        self.recording_btn.setText(_translate("flow_ai_dialog", "Recording​"))
        self.complexity.setText(_translate("flow_ai_dialog", "Complexity​"))
        self.basic_btn.setText(_translate("flow_ai_dialog", "Basic"))
        self.advanced_btn.setText(_translate("flow_ai_dialog", "Advanced​"))
        self.design_for.setText(_translate("flow_ai_dialog", "Design For​"))
        self.fine_tune_label.setText(_translate("flow_ai_dialog", "Optimize Design"))
        self.describe_textEdit.setHtml(_translate("flow_ai_dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.describe_textEdit.setPlaceholderText(_translate("flow_ai_dialog", "Describe your target design​"))
        self.count_limit_label.setText(_translate("flow_ai_dialog", "0/100"))
        self.generate_btn.setText(_translate("flow_ai_dialog", "Generate Flow Project​"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.design), _translate("flow_ai_dialog", "Tab 2"))
