# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\input_text_generate_flow_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputTextGenerateFlowDialog(object):
    def setupUi(self, InputTextGenerateFlowDialog):
        InputTextGenerateFlowDialog.setObjectName("InputTextGenerateFlowDialog")
        InputTextGenerateFlowDialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputTextGenerateFlowDialog.sizePolicy().hasHeightForWidth())
        InputTextGenerateFlowDialog.setSizePolicy(sizePolicy)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(InputTextGenerateFlowDialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 20, 351, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(InputTextGenerateFlowDialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 250, 156, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(InputTextGenerateFlowDialog)
        QtCore.QMetaObject.connectSlotsByName(InputTextGenerateFlowDialog)

    def retranslateUi(self, InputTextGenerateFlowDialog):
        _translate = QtCore.QCoreApplication.translate
        InputTextGenerateFlowDialog.setWindowTitle(_translate("InputTextGenerateFlowDialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InputTextGenerateFlowDialog = QtWidgets.QDialog()
    ui = Ui_InputTextGenerateFlowDialog()
    ui.setupUi(InputTextGenerateFlowDialog)
    InputTextGenerateFlowDialog.show()
    sys.exit(app.exec_())
