# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modify_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modifyPasswordDialog(object):
    def setupUi(self, modifyPasswordDialog):
        modifyPasswordDialog.setObjectName("modifyPasswordDialog")
        modifyPasswordDialog.setEnabled(True)
        modifyPasswordDialog.resize(400, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(modifyPasswordDialog.sizePolicy().hasHeightForWidth())
        modifyPasswordDialog.setSizePolicy(sizePolicy)
        modifyPasswordDialog.setMinimumSize(QtCore.QSize(400, 80))
        modifyPasswordDialog.setMaximumSize(QtCore.QSize(400, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        modifyPasswordDialog.setFont(font)
        modifyPasswordDialog.setSizeGripEnabled(False)
        modifyPasswordDialog.setModal(False)
        self.layoutWidget = QtWidgets.QWidget(modifyPasswordDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 382, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.lineEditOriginalPassword = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOriginalPassword.sizePolicy().hasHeightForWidth())
        self.lineEditOriginalPassword.setSizePolicy(sizePolicy)
        self.lineEditOriginalPassword.setMaximumSize(QtCore.QSize(180, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.lineEditOriginalPassword.setFont(font)
        self.lineEditOriginalPassword.setMaxLength(12)
        self.lineEditOriginalPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditOriginalPassword.setObjectName("lineEditOriginalPassword")
        self.horizontalLayout.addWidget(self.lineEditOriginalPassword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.lineEditNewPassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNewPassword.setMaximumSize(QtCore.QSize(180, 24))
        self.lineEditNewPassword.setMaxLength(12)
        self.lineEditNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditNewPassword.setObjectName("lineEditNewPassword")
        self.horizontalLayout_9.addWidget(self.lineEditNewPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditConfirmPassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditConfirmPassword.setMaximumSize(QtCore.QSize(180, 24))
        self.lineEditConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditConfirmPassword.setObjectName("lineEditConfirmPassword")
        self.horizontalLayout_2.addWidget(self.lineEditConfirmPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(380, 30))
        self.buttonBox.setMaximumSize(QtCore.QSize(380, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("        QPushButton {\n"
"        font: 9pt \"Calibri\";\n"
"        width: 120px;\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 5 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(modifyPasswordDialog)
        self.buttonBox.accepted.connect(modifyPasswordDialog.accept)
        self.buttonBox.rejected.connect(modifyPasswordDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(modifyPasswordDialog)

    def retranslateUi(self, modifyPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        modifyPasswordDialog.setWindowTitle(_translate("modifyPasswordDialog", "Dialog"))
        self.label_1.setText(_translate("modifyPasswordDialog", "Please enter original password"))
        self.label.setText(_translate("modifyPasswordDialog", "Please enter new password"))
        self.label_2.setText(_translate("modifyPasswordDialog", "Please confirm new password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modifyPasswordDialog = QtWidgets.QDialog()
    ui = Ui_modifyPasswordDialog()
    ui.setupUi(modifyPasswordDialog)
    modifyPasswordDialog.show()
    sys.exit(app.exec_())
