# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'more_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_more_project(object):
    def setupUi(self, more_project):
        more_project.setObjectName("more_project")
        more_project.resize(320, 520)
        more_project.setMinimumSize(QtCore.QSize(320, 510))
        more_project.setMaximumSize(QtCore.QSize(1000, 520))
        self.scrollArea = QtWidgets.QScrollArea(more_project)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 300, 500))
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 500))
        self.scrollArea.setMaximumSize(QtCore.QSize(1000, 500))
        self.scrollArea.setStyleSheet("background-color: #474747;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(more_project)
        QtCore.QMetaObject.connectSlotsByName(more_project)

    def retranslateUi(self, more_project):
        _translate = QtCore.QCoreApplication.translate
        more_project.setWindowTitle(_translate("more_project", "Recent Projects"))
