# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'node_band_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_node_band_select(object):
    def setupUi(self, node_band_select):
        node_band_select.setObjectName("node_band_select")
        node_band_select.setEnabled(True)
        node_band_select.resize(424, 167)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(node_band_select.sizePolicy().hasHeightForWidth())
        node_band_select.setSizePolicy(sizePolicy)
        node_band_select.setMinimumSize(QtCore.QSize(0, 0))
        node_band_select.setMaximumSize(QtCore.QSize(5100, 1950))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        node_band_select.setFont(font)
        node_band_select.setSizeGripEnabled(False)
        node_band_select.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(node_band_select)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BandLayout = QtWidgets.QHBoxLayout()
        self.BandLayout.setSpacing(100)
        self.BandLayout.setObjectName("BandLayout")
        self.label_1 = QtWidgets.QLabel(node_band_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.BandLayout.addWidget(self.label_1)
        self.comboBox = QtWidgets.QComboBox(node_band_select)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.BandLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.BandLayout)
        self.MaxBandLayout = QtWidgets.QHBoxLayout()
        self.MaxBandLayout.setSpacing(100)
        self.MaxBandLayout.setObjectName("MaxBandLayout")
        self.label_3 = QtWidgets.QLabel(node_band_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.MaxBandLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(node_band_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_2.setSizeIncrement(QtCore.QSize(-1, 0))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.MaxBandLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.MaxBandLayout)
        self.ChannelLayout = QtWidgets.QHBoxLayout()
        self.ChannelLayout.setSpacing(80)
        self.ChannelLayout.setObjectName("ChannelLayout")
        self.label_2 = QtWidgets.QLabel(node_band_select)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.ChannelLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(node_band_select)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(node_band_select)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(node_band_select)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.ChannelLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.ChannelLayout)
        self.ControlInputLayout = QtWidgets.QHBoxLayout()
        self.ControlInputLayout.setSpacing(100)
        self.ControlInputLayout.setObjectName("ControlInputLayout")
        self.label_4 = QtWidgets.QLabel(node_band_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.ControlInputLayout.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(node_band_select)
        self.comboBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox QAbstractItemView\n"
"{\n"
"     border: 1px solid rgb(161,161,161);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height: 24px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected\n"
"{    \n"
"    background-color: rgba(54, 98, 180);\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.ControlInputLayout.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.ControlInputLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(node_band_select)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 75 9pt \"Calibri\";\n"
"    font-weight: bold;\n"
"    background: gray;\n"
"    color: white;\n"
"\n"
"    border-radius: 0px;\n"
"    \n"
"    width: 120px;\n"
"    height: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background:  #595959;\n"
"    color: gray;\n"
"}\n"
"\n"
"QPushButton:enabled {\n"
"    background: gray;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: gray;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: lightgray;\n"
"    color: black;\n"
"    border-width: 3px;\n"
"    border-style: solid;\n"
"    border-color: gray;\n"
"}\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(node_band_select)
        self.buttonBox.rejected.connect(node_band_select.reject) # type: ignore
        self.buttonBox.accepted.connect(node_band_select.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(node_band_select)

    def retranslateUi(self, node_band_select):
        _translate = QtCore.QCoreApplication.translate
        node_band_select.setWindowTitle(_translate("node_band_select", "Dialog"))
        self.label_1.setText(_translate("node_band_select", "Band"))
        self.comboBox.setItemText(0, _translate("node_band_select", "1"))
        self.comboBox.setItemText(1, _translate("node_band_select", "2"))
        self.comboBox.setItemText(2, _translate("node_band_select", "3"))
        self.comboBox.setItemText(3, _translate("node_band_select", "4"))
        self.comboBox.setItemText(4, _translate("node_band_select", "5"))
        self.comboBox.setItemText(5, _translate("node_band_select", "6"))
        self.comboBox.setItemText(6, _translate("node_band_select", "7"))
        self.comboBox.setItemText(7, _translate("node_band_select", "8"))
        self.label_3.setText(_translate("node_band_select", "Max Band"))
        self.lineEdit_2.setText(_translate("node_band_select", "1"))
        self.lineEdit_2.setPlaceholderText(_translate("node_band_select", "1"))
        self.label_2.setText(_translate("node_band_select", "Channel                                                        "))
        self.pushButton.setText(_translate("node_band_select", "-"))
        self.lineEdit.setText(_translate("node_band_select", "1"))
        self.lineEdit.setPlaceholderText(_translate("node_band_select", "1"))
        self.pushButton_2.setText(_translate("node_band_select", "+"))
        self.label_4.setText(_translate("node_band_select", "Control Iuput"))
        self.comboBox_2.setItemText(0, _translate("node_band_select", "Disabled"))
        self.comboBox_2.setItemText(1, _translate("node_band_select", "Enabled"))
