# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profile_update_Dialog(object):
    def setupUi(self, profile_update_Dialog):
        profile_update_Dialog.setObjectName("profile_update_Dialog")
        profile_update_Dialog.setEnabled(True)
        profile_update_Dialog.resize(400, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profile_update_Dialog.sizePolicy().hasHeightForWidth())
        profile_update_Dialog.setSizePolicy(sizePolicy)
        profile_update_Dialog.setMinimumSize(QtCore.QSize(400, 130))
        profile_update_Dialog.setMaximumSize(QtCore.QSize(400, 130))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        profile_update_Dialog.setFont(font)
        profile_update_Dialog.setSizeGripEnabled(False)
        profile_update_Dialog.setModal(False)
        self.pushButton = QtWidgets.QPushButton(profile_update_Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 70, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(profile_update_Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 70, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(profile_update_Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 431, 61))
        self.label.setObjectName("label")

        self.retranslateUi(profile_update_Dialog)
        QtCore.QMetaObject.connectSlotsByName(profile_update_Dialog)

    def retranslateUi(self, profile_update_Dialog):
        _translate = QtCore.QCoreApplication.translate
        profile_update_Dialog.setWindowTitle(_translate("profile_update_Dialog", "Dialog"))
        self.pushButton.setText(_translate("profile_update_Dialog", "USB"))
        self.pushButton_2.setText(_translate("profile_update_Dialog", "UART"))
        self.label.setText(_translate("profile_update_Dialog", "Sorry, your profile is old, please select the button below to update"))
