# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\remove_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_removePasswordDialog(object):
    def setupUi(self, removePasswordDialog):
        removePasswordDialog.setObjectName("removePasswordDialog")
        removePasswordDialog.setEnabled(True)
        removePasswordDialog.resize(420, 110)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(removePasswordDialog.sizePolicy().hasHeightForWidth())
        removePasswordDialog.setSizePolicy(sizePolicy)
        removePasswordDialog.setMinimumSize(QtCore.QSize(420, 80))
        removePasswordDialog.setMaximumSize(QtCore.QSize(420, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        removePasswordDialog.setFont(font)
        removePasswordDialog.setSizeGripEnabled(False)
        removePasswordDialog.setModal(False)
        self.layoutWidget = QtWidgets.QWidget(removePasswordDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 391, 88))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMaximumSize(QtCore.QSize(180, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setMaxLength(12)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout.addWidget(self.lineEditPassword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(380, 30))
        self.buttonBox.setMaximumSize(QtCore.QSize(380, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("        QPushButton {\n"
"        font: 9pt \"Calibri\";\n"
"        width: 120px;\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 5 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(removePasswordDialog)
        self.buttonBox.accepted.connect(removePasswordDialog.accept)
        self.buttonBox.rejected.connect(removePasswordDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(removePasswordDialog)

    def retranslateUi(self, removePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        removePasswordDialog.setWindowTitle(_translate("removePasswordDialog", "Dialog"))
        self.label_1.setText(_translate("removePasswordDialog", "Please enter the password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    removePasswordDialog = QtWidgets.QDialog()
    ui = Ui_removePasswordDialog()
    ui.setupUi(removePasswordDialog)
    removePasswordDialog.show()
    sys.exit(app.exec_())
