# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_flow_diff.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(556, 129)
        self.chg_proj_push_btn = QtWidgets.QPushButton(Form)
        self.chg_proj_push_btn.setGeometry(QtCore.QRect(270, 60, 75, 23))
        self.chg_proj_push_btn.setObjectName("chg_proj_push_btn")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(370, 30, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.orig_proj_line_edit = QtWidgets.QLineEdit(Form)
        self.orig_proj_line_edit.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.orig_proj_line_edit.setReadOnly(True)
        self.orig_proj_line_edit.setObjectName("orig_proj_line_edit")
        self.chg_proj_label = QtWidgets.QLabel(Form)
        self.chg_proj_label.setGeometry(QtCore.QRect(50, 60, 91, 20))
        self.chg_proj_label.setObjectName("chg_proj_label")
        self.orig_proj_push_btn = QtWidgets.QPushButton(Form)
        self.orig_proj_push_btn.setGeometry(QtCore.QRect(270, 30, 75, 23))
        self.orig_proj_push_btn.setObjectName("orig_proj_push_btn")
        self.orig_proj_label = QtWidgets.QLabel(Form)
        self.orig_proj_label.setGeometry(QtCore.QRect(50, 30, 91, 20))
        self.orig_proj_label.setObjectName("orig_proj_label")
        self.chg_proj_line_edit = QtWidgets.QLineEdit(Form)
        self.chg_proj_line_edit.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.chg_proj_line_edit.setReadOnly(True)
        self.chg_proj_line_edit.setObjectName("chg_proj_line_edit")
        self.use_edited_flow_check_box = QtWidgets.QCheckBox(Form)
        self.use_edited_flow_check_box.setGeometry(QtCore.QRect(100, 90, 361, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.use_edited_flow_check_box.setFont(font)
        self.use_edited_flow_check_box.setStyleSheet("QCheckBox {\n"
"                    color: white;\n"
"                    font-family: Calibri;\n"
"                }\n"
"                QCheckBox::indicator{\n"
"                    border: 2px solid #b1b1b1;\n"
"                    background-color: white;\n"
"                }\n"
"                \n"
"                QCheckBox::indicator:checked {\n"
"                    background-color: black;\n"
"                }\n"
"                \n"
"                \n"
"                QCheckBox::indicator:unchecked {\n"
"                    background-color: white;\n"
"                }")
        self.use_edited_flow_check_box.setObjectName("use_edited_flow_check_box")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chg_proj_push_btn.setText(_translate("Form", "open"))
        self.chg_proj_label.setText(_translate("Form", "Changed project"))
        self.orig_proj_push_btn.setText(_translate("Form", "open"))
        self.orig_proj_label.setText(_translate("Form", "Original project"))
        self.use_edited_flow_check_box.setText(_translate("Form", "Use the currently edited flow as changed project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
