# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usb_runtime_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_usb_runtime_select_Dialog(object):
    def setupUi(self, usb_runtime_select_Dialog):
        usb_runtime_select_Dialog.setObjectName("usb_runtime_select_Dialog")
        usb_runtime_select_Dialog.setEnabled(True)
        usb_runtime_select_Dialog.resize(450, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(usb_runtime_select_Dialog.sizePolicy().hasHeightForWidth())
        usb_runtime_select_Dialog.setSizePolicy(sizePolicy)
        usb_runtime_select_Dialog.setMinimumSize(QtCore.QSize(450, 200))
        usb_runtime_select_Dialog.setMaximumSize(QtCore.QSize(450, 200))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        usb_runtime_select_Dialog.setFont(font)
        usb_runtime_select_Dialog.setSizeGripEnabled(False)
        usb_runtime_select_Dialog.setModal(False)
        self.Group0_Profile = QtWidgets.QGroupBox(usb_runtime_select_Dialog)
        self.Group0_Profile.setGeometry(QtCore.QRect(10, 20, 431, 76))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group0_Profile.sizePolicy().hasHeightForWidth())
        self.Group0_Profile.setSizePolicy(sizePolicy)
        self.Group0_Profile.setMinimumSize(QtCore.QSize(0, 0))
        self.Group0_Profile.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.Group0_Profile.setFont(font)
        self.Group0_Profile.setStyleSheet("QGroupBox{\n"
"    font: 25 10pt \"Calibri\";\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.Group0_Profile.setFlat(True)
        self.Group0_Profile.setCheckable(False)
        self.Group0_Profile.setObjectName("Group0_Profile")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Group0_Profile)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 431, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.hBoxLayout_Profile_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.hBoxLayout_Profile_3.setContentsMargins(10, 10, 10, 10)
        self.hBoxLayout_Profile_3.setSpacing(10)
        self.hBoxLayout_Profile_3.setObjectName("hBoxLayout_Profile_3")
        self.upload = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setMinimumSize(QtCore.QSize(0, 0))
        self.upload.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.upload.setFont(font)
        self.upload.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.upload.setObjectName("upload")
        self.hBoxLayout_Profile_3.addWidget(self.upload)
        self.flash = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flash.sizePolicy().hasHeightForWidth())
        self.flash.setSizePolicy(sizePolicy)
        self.flash.setMinimumSize(QtCore.QSize(0, 0))
        self.flash.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.flash.setFont(font)
        self.flash.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:disabled {  \n"
"         background-color: #a1a1a1;\n"
"         color: #636363;\n"
"        }  ")
        self.flash.setObjectName("flash")
        self.hBoxLayout_Profile_3.addWidget(self.flash)
        self.only = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.only.sizePolicy().hasHeightForWidth())
        self.only.setSizePolicy(sizePolicy)
        self.only.setMinimumSize(QtCore.QSize(0, 0))
        self.only.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.only.setFont(font)
        self.only.setStyleSheet("        QPushButton {\n"
"        color: black;\n"
"        border-color: darkGray;\n"
"        border-style: solid;\n"
"        border-radius: 2;\n"
"        padding: 2 px;\n"
"        background-color: lightGray;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: darkGray;\n"
"        }\n"
"        QPushButton:Pressed {\n"
"        background-color: darkGray;\n"
"        }")
        self.only.setObjectName("only")
        self.hBoxLayout_Profile_3.addWidget(self.only)
        self.verify_bar = QtWidgets.QProgressBar(usb_runtime_select_Dialog)
        self.verify_bar.setGeometry(QtCore.QRect(120, 140, 271, 16))
        self.verify_bar.setProperty("value", 0)
        self.verify_bar.setObjectName("verify_bar")
        self.convert_bar = QtWidgets.QProgressBar(usb_runtime_select_Dialog)
        self.convert_bar.setGeometry(QtCore.QRect(120, 110, 271, 16))
        self.convert_bar.setProperty("value", 0)
        self.convert_bar.setObjectName("convert_bar")
        self.label = QtWidgets.QLabel(usb_runtime_select_Dialog)
        self.label.setGeometry(QtCore.QRect(50, 110, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(usb_runtime_select_Dialog)
        self.label_2.setGeometry(QtCore.QRect(63, 140, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(usb_runtime_select_Dialog)
        self.label_3.setGeometry(QtCore.QRect(53, 170, 71, 20))
        self.label_3.setObjectName("label_3")
        self.upload_bar = QtWidgets.QProgressBar(usb_runtime_select_Dialog)
        self.upload_bar.setGeometry(QtCore.QRect(120, 170, 271, 16))
        self.upload_bar.setProperty("value", 0)
        self.upload_bar.setObjectName("upload_bar")

        self.retranslateUi(usb_runtime_select_Dialog)
        QtCore.QMetaObject.connectSlotsByName(usb_runtime_select_Dialog)

    def retranslateUi(self, usb_runtime_select_Dialog):
        _translate = QtCore.QCoreApplication.translate
        usb_runtime_select_Dialog.setWindowTitle(_translate("usb_runtime_select_Dialog", "Dialog"))
        self.Group0_Profile.setTitle(_translate("usb_runtime_select_Dialog", "Connect Select"))
        self.upload.setText(_translate("usb_runtime_select_Dialog", "Upload design (RAM)"))
        self.flash.setText(_translate("usb_runtime_select_Dialog", "Upload design (FLASH)"))
        self.only.setText(_translate("usb_runtime_select_Dialog", "Connect Only"))
        self.label.setText(_translate("usb_runtime_select_Dialog", "convert："))
        self.label_2.setText(_translate("usb_runtime_select_Dialog", "verify："))
        self.label_3.setText(_translate("usb_runtime_select_Dialog", "upload："))
