# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_expired_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_expired_box(object):
    def setupUi(self, user_expired_box):
        user_expired_box.setObjectName("user_expired_box")
        user_expired_box.resize(340, 150)
        user_expired_box.setMinimumSize(QtCore.QSize(340, 150))
        user_expired_box.setMaximumSize(QtCore.QSize(340, 150))
        self.horizontalLayoutWidget = QtWidgets.QWidget(user_expired_box)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 321, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signin = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.signin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signin.setStyleSheet("QPushButton {\n"
"    font-size: 14px;\n"
"    background-color: #2D8CFF;  /* 品牌蓝色 */\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 10px 10px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    min-width: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1A73E8;  /* 悬停加深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1557B0;  /* 按压效果 */\n"
"}")
        self.signin.setObjectName("signin")
        self.horizontalLayout.addWidget(self.signin)
        self.contactus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.contactus.setMinimumSize(QtCore.QSize(70, 0))
        self.contactus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactus.setStyleSheet("QPushButton {\n"
"    font-size: 14px;\n"
"       background-color: #d3d3d3;  /* 浅灰背景 */\n"
"    color: #303030; \n"
"    border-radius: 6px;\n"
"    padding: 10px 10px;\n"
"    border: none;\n"
"    min-width: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b3b3b3;  /* 悬停加深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b3b3b3;  /* 按压效果 */\n"
"}")
        self.contactus.setObjectName("contactus")
        self.horizontalLayout.addWidget(self.contactus)
        self.close = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.close.setMinimumSize(QtCore.QSize(70, 0))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setStyleSheet("QPushButton {\n"
"    font-size: 14px;\n"
"       background-color: #d3d3d3;  /* 浅灰背景 */\n"
"    color: #303030; \n"
"    border-radius: 6px;\n"
"    padding: 10px 10px;\n"
"    border: none;\n"
"    min-width: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b3b3b3;  /* 悬停加深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b3b3b3;  /* 按压效果 */\n"
"}")
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.verticalLayoutWidget = QtWidgets.QWidget(user_expired_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 16px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_msg = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        self.label_msg.setFont(font)
        self.label_msg.setStyleSheet("font-size: 16px;")
        self.label_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msg.setWordWrap(True)
        self.label_msg.setObjectName("label_msg")
        self.verticalLayout.addWidget(self.label_msg)

        self.retranslateUi(user_expired_box)
        QtCore.QMetaObject.connectSlotsByName(user_expired_box)

    def retranslateUi(self, user_expired_box):
        _translate = QtCore.QCoreApplication.translate
        user_expired_box.setWindowTitle(_translate("user_expired_box", "Dialog"))
        self.signin.setText(_translate("user_expired_box", "Sign in"))
        self.contactus.setText(_translate("user_expired_box", "Contact Us"))
        self.close.setText(_translate("user_expired_box", "Close"))
        self.label.setText(_translate("user_expired_box", "🚨 Your trial has expired!"))
        self.label_msg.setText(_translate("user_expired_box", "Please sign up your account or contact us"))
