# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_pane.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_pane(object):
    def setupUi(self, user_pane):
        user_pane.setObjectName("user_pane")
        user_pane.resize(276, 231)
        user_pane.setMinimumSize(QtCore.QSize(240, 150))
        user_pane.setMaximumSize(QtCore.QSize(3600, 1500))
        user_pane.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        user_pane.setStyleSheet("border-radius: 4px;\n"
"background-color: #1f1f1f;")
        self.widget = QtWidgets.QWidget(user_pane)
        self.widget.setGeometry(QtCore.QRect(10, 10, 259, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.action = QtWidgets.QWidget(self.widget)
        self.action.setObjectName("action")
        self.text = QtWidgets.QLabel(self.action)
        self.text.setGeometry(QtCore.QRect(20, 30, 221, 33))
        self.text.setStyleSheet("")
        self.text.setObjectName("text")
        self.signin = QtWidgets.QPushButton(self.action)
        self.signin.setGeometry(QtCore.QRect(20, 80, 221, 40))
        self.signin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signin.setStyleSheet("QPushButton {\n"
"    background-color: #1283DC;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 12px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0E6FBC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0A5A99;\n"
"}")
        self.signin.setObjectName("signin")
        self.text_2 = QtWidgets.QLabel(self.action)
        self.text_2.setGeometry(QtCore.QRect(20, 140, 221, 33))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.text_2.setFont(font)
        self.text_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_2.setStyleSheet("text-align: center; \n"
"font-size: 14px;")
        self.text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_2.setWordWrap(True)
        self.text_2.setObjectName("text_2")
        self.verticalLayout.addWidget(self.action)
        self.info = QtWidgets.QWidget(self.widget)
        self.info.setStyleSheet("border-radius: 5px;\n"
"font-family: \'Segoe UI\', sans-serif;\n"
"font-size: 12px;\n"
"color: #CCCCCC;")
        self.info.setObjectName("info")
        self.tier = QtWidgets.QLabel(self.info)
        self.tier.setGeometry(QtCore.QRect(15, 100, 201, 21))
        self.tier.setStyleSheet("")
        self.tier.setObjectName("tier")
        self.expired = QtWidgets.QLabel(self.info)
        self.expired.setGeometry(QtCore.QRect(15, 70, 241, 21))
        self.expired.setStyleSheet("")
        self.expired.setObjectName("expired")
        self.email = QtWidgets.QLabel(self.info)
        self.email.setGeometry(QtCore.QRect(60, 10, 191, 43))
        self.email.setObjectName("email")
        self.pushButton = QtWidgets.QPushButton(self.info)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/user-avatar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.info)
        self.line.setGeometry(QtCore.QRect(7, 60, 251, 2))
        self.line.setStyleSheet("background-color: #5f5f5f; border: none; height: 2px;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.info)
        self.line_2.setGeometry(QtCore.QRect(7, 160, 251, 2))
        self.line_2.setStyleSheet("background-color: #5f5f5f; border: none; height: 2px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.signout = QtWidgets.QPushButton(self.info)
        self.signout.setGeometry(QtCore.QRect(0, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.signout.setFont(font)
        self.signout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signout.setStyleSheet("color: #FF5252;")
        self.signout.setObjectName("signout")
        self.feedback = QtWidgets.QPushButton(self.info)
        self.feedback.setGeometry(QtCore.QRect(10, 130, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.feedback.setFont(font)
        self.feedback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback.setStyleSheet("color: #7FD6C2;")
        self.feedback.setObjectName("feedback")
        self.verticalLayout.addWidget(self.info)

        self.retranslateUi(user_pane)
        QtCore.QMetaObject.connectSlotsByName(user_pane)

    def retranslateUi(self, user_pane):
        _translate = QtCore.QCoreApplication.translate
        user_pane.setWindowTitle(_translate("user_pane", "Dialog"))
        self.text.setText(_translate("user_pane", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Sign in with your Flow account</span></p></body></html>"))
        self.signin.setText(_translate("user_pane", "Sign in"))
        self.text_2.setText(_translate("user_pane", "<html><head/><body><p><span style=\" font-size:10pt;\">Not signed-in users, Flow Studio will expire in [days] days​</span></p></body></html>"))
        self.tier.setText(_translate("user_pane", "Plan"))
        self.expired.setText(_translate("user_pane", "Expired Date:"))
        self.email.setText(_translate("user_pane", "Jason.Zhong@tymphany.com"))
        self.signout.setText(_translate("user_pane", "Sign out"))
        self.feedback.setText(_translate("user_pane", "Submit Feedback"))
