__all__ = [
    'PERMISSION_ERROR_WHEN_CREATE_TEMP_FOLDER',
    'PERMISSION_ERROR_WHEN_CREATE_TEMP_FILE'
]

PERMISSION_ERROR_WHEN_CREATE_TEMP_FOLDER = 100001
PERMISSION_ERROR_WHEN_CREATE_TEMP_FILE = 100002
