"""
under directory: ~/FlowStudioPy/implementation/flowstudio
temporary build command is: pyinstaller -F -p ..\..\FlowStudioPy\ main.py

-F into a single .exe under /dist
-D into mutiple module folder under /dist
-p path, we need the external module in the project
-w shut down command line window
"""
VERSION = "2.3.5-pro"

import json
import shutil
import os
import subprocess


class Manager(object):
    def get_all_url_list(self):
        with open('constant.json', 'r') as file:
            data = json.load(file)
        tier = data['tier']
        env = data['env']
        domain = data[env][tier]
        common_urls = {}
        distribution_urls = {}
        for key, value in data["common_urls"].items():
            common_urls[key] = domain["domain"] + value
        for key, value in data["distribution_urls"].items():
            distribution_urls[key] = domain["distribution_domain"] + value

        return common_urls, distribution_urls

class FileFill():
    def __init__(self):
        self.newFile = open("build_NSIS.nsi", 'w', encoding='gbk')
        self.handlerSectionBefore()
        self.handleSectionContent('dist','main')
        self.handleSectionAfter()
        self.handleSectionUninstall('dist')

    def handlerSectionBefore(self):
        with open('constant.json', 'r') as file:
            data = json.load(file)
        tier = data.get('tier', 'free')
        beforText = ''
        if tier == 'free':
            beforText = '; Script generated by the HM NIS Edit Script Wizard.\n\n' \
                        '; HM NIS Edit Wizard helper defines\n' \
                        '!define PRODUCT_NAME "Flow Studio"\n' \
                        '!define PRODUCT_VERSION %s\n' \
                        '!define PRODUCT_PUBLISHER "Tymphany"\n' \
                        '!define PRODUCT_WEB_SITE "http://www.tymphany.com"\n' \
                        '!define PRODUCT_DIR_REGKEY "Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\main.exe"\n' \
                        '!define PRODUCT_INSTALL_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Install\\${PRODUCT_NAME}"\n' \
                        r'!define PRODUCT_UNINST_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${PRODUCT_NAME}"' \
                        '\n\n; MUI 1.67 compatible ------\n' \
                        '!include "MUI.nsh"\n' \
                        '!include "nsDialogs.nsh"\n' \
                        '!include "LogicLib.nsh"\n\n' \
                        '; MUI Settings\n' \
                        '!define MUI_ABORTWARNING\n' \
                        '!define MUI_ICON "..\\resources\\main-theme.ico"\n\n' \
                        '; Welcome page\n' \
                        '!insertmacro MUI_PAGE_WELCOME\n' \
                        '; License page\n' \
                        '!insertmacro MUI_PAGE_LICENSE "..\\License.txt"\n' \
                        '; Privacy Policy page\n' \
                        'Page custom PrivacyPolicyPage PrivacyPolicyPageLeave\n' \
                        '; Directory page\n' \
                        '!insertmacro MUI_PAGE_DIRECTORY\n' \
                        '; Instfiles page\n' \
                        '!insertmacro MUI_PAGE_INSTFILES\n\n' \
                        '; Language files\n' \
                        '!insertmacro MUI_LANGUAGE "English"\n\n' \
                        '; MUI end ------\n\n' \
                        'Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"\n' \
                        'OutFile "Flow Studio %s.exe"\n' \
                        '!define MUI_PAGE_CUSTOMFUNCTION_show Pageshow \n' \
                        'InstallDir "C:\\FlowStudio"\n' \
                        'InstallDirRegKey HKCU "Software\\FlowStudio" "" \n' \
                        'ShowUnInstDetails  show\n' \
                        'ShowInstDetails show\n' % (VERSION, VERSION)
        else:
            beforText = '; Script generated by the HM NIS Edit Script Wizard.\n\n' \
                        '; HM NIS Edit Wizard helper defines\n' \
                        '!define PRODUCT_NAME "Flow Studio Pro"\n' \
                        '!define PRODUCT_VERSION %s\n' \
                        '!define PRODUCT_PUBLISHER "Tymphany"\n' \
                        '!define PRODUCT_WEB_SITE "http://www.tymphany.com"\n' \
                        '!define PRODUCT_DIR_REGKEY "Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\main.exe"\n' \
                        '!define PRODUCT_INSTALL_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Install\\${PRODUCT_NAME}"\n' \
                        r'!define PRODUCT_UNINST_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${PRODUCT_NAME}"' \
                        '\n\n; MUI 1.67 compatible ------\n' \
                        '!include "MUI.nsh"\n' \
                        '!include "nsDialogs.nsh"\n' \
                        '!include "LogicLib.nsh"\n\n' \
                        '; MUI Settings\n' \
                        '!define MUI_ABORTWARNING\n' \
                        '!define MUI_ICON "..\\resources\\main-theme.ico"\n\n' \
                        '; Welcome page\n' \
                        '!insertmacro MUI_PAGE_WELCOME\n' \
                        '; License page\n' \
                        '!insertmacro MUI_PAGE_LICENSE "..\\License.txt"\n' \
                        '; Privacy Policy page\n' \
                        'Page custom PrivacyPolicyPage PrivacyPolicyPageLeave\n' \
                        '; Directory page\n' \
                        '!insertmacro MUI_PAGE_DIRECTORY\n' \
                        '; Instfiles page\n' \
                        '!insertmacro MUI_PAGE_INSTFILES\n\n' \
                        '; Language files\n' \
                        '!insertmacro MUI_LANGUAGE "English"\n\n' \
                        '; MUI end ------\n\n' \
                        'Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"\n' \
                        'OutFile "Flow Studio %s Pro.exe"\n' \
                        '!define MUI_PAGE_CUSTOMFUNCTION_show Pageshow \n' \
                        'InstallDir "C:\\FlowStudio_Pro"\n' \
                        'InstallDirRegKey HKCU "Software\\FlowStudioPro" "" \n' \
                        'ShowUnInstDetails  show\n' \
                        'ShowInstDetails show\n' % (VERSION, VERSION)
        self.newFile.write(beforText)

        # Add Privacy Policy variable
        varDeclarations = '''
    Var Dialog
    Var LinkLabel
    Var CheckBox
    '''
        self.newFile.write(varDeclarations)

        # Add Privacy Policy function
        privacyPolicyFunctions = ''
        if tier == 'free':
            privacyPolicyFunctions = '''
        Function OpenPrivacyPolicy
            ExecShell "open" "https://flowdsp.tymecho.com/#/privacyPolicy"
        FunctionEnd

        Function PrivacyPolicyPage
            !insertmacro MUI_HEADER_TEXT "Privacy Policy" "Please read our privacy policy to continue."

            nsDialogs::Create 1018
            Pop $Dialog

            ${If} $Dialog == error
                Abort
            ${EndIf}

            ${NSD_CreateLabel} 0 0 100% 30u "Please visit the following link to read our Privacy Policy:"
            Pop $0

            ${NSD_CreateLink} 0 35u 100% 15u "https://flowdsp.tymecho.com/#/privacyPolicy"
            Pop $LinkLabel
            ${NSD_OnClick} $LinkLabel OpenPrivacyPolicy

            ${NSD_CreateLabel} 0 60u 100% 30u "After you have read the Privacy Policy, please check the box below to continue with the installation."
            Pop $0

            ${NSD_CreateCheckbox} 0 100u 100% 15u "I have read and accept the Privacy Policy"
            Pop $CheckBox

            nsDialogs::Show
        FunctionEnd

        Function PrivacyPolicyPageLeave
            ${NSD_GetState} $CheckBox $0
            ${If} $0 != ${BST_CHECKED}
                MessageBox MB_ICONEXCLAMATION "You must accept the Privacy Policy to continue the installation."
                Abort
            ${EndIf}
        FunctionEnd
        '''
        else:
            privacyPolicyFunctions = '''
        Function OpenPrivacyPolicy
            ExecShell "open" "https://beta.tymecho.com/#/privacyPolicy"
        FunctionEnd

        Function PrivacyPolicyPage
            !insertmacro MUI_HEADER_TEXT "Privacy Policy" "Please read our privacy policy to continue."

            nsDialogs::Create 1018
            Pop $Dialog

            ${If} $Dialog == error
                Abort
            ${EndIf}

            ${NSD_CreateLabel} 0 0 100% 30u "Please visit the following link to read our Privacy Policy:"
            Pop $0

            ${NSD_CreateLink} 0 35u 100% 15u "https://beta.tymecho.com/#/privacyPolicy"
            Pop $LinkLabel
            ${NSD_OnClick} $LinkLabel OpenPrivacyPolicy

            ${NSD_CreateLabel} 0 60u 100% 30u "After you have read the Privacy Policy, please check the box below to continue with the installation."
            Pop $0

            ${NSD_CreateCheckbox} 0 100u 100% 15u "I have read and accept the Privacy Policy"
            Pop $CheckBox

            nsDialogs::Show
        FunctionEnd

        Function PrivacyPolicyPageLeave
            ${NSD_GetState} $CheckBox $0
            ${If} $0 != ${BST_CHECKED}
                MessageBox MB_ICONEXCLAMATION "You must accept the Privacy Policy to continue the installation."
                Abort
            ${EndIf}
        FunctionEnd
        '''
        self.newFile.write(privacyPolicyFunctions)

    def handleSectionContent(self,path,main):
        self.newFile.write('\n\n\n')
        rootPath=[]
        i=0
        with open('constant.json', 'r') as file:
            data = json.load(file)
        tier = data.get('tier', 'free')
        for root, dirs, files in os.walk(path):
            if root == path:
                for dir in dirs:
                    rootPath.append(root + '\\' + dir)
                continue
            if root in rootPath:
                i=i+1
                if root != rootPath[0]:
                    self.newFile.write('SectionEnd'+'\n\n')
                self.newFile.write('Section "'+root.split('\\')[-1]+'" SEC0'+str(i)+"\n")

            if len(files) != 0:
                writetext = '  SetOutPath "$INSTDIR' + root.split(path)[1] + '"\n'
                self.newFile.write(writetext)

                for file in files:
                    if '.' in file and file.split('.')[1] == 'zip':
                        self.newFile.write('  SetOverwrite try'+'\n')

                    writetext = '  File "' + os.path.join(root, file) + '"\n'
                    self.newFile.write(writetext)

                    if file == main+'.exe' and root.split('\\')[-1] == main:
                        if tier == 'free':
                            self.newFile.write('  SetShellVarContext all' + '\n')
                            self.newFile.write('  CreateDirectory "$SMPROGRAMS\FlowStudio"'+'\n')
                            self.newFile.write('  CreateShortCut "$SMPROGRAMS\FlowStudio\Flow Studio.lnk" "$INSTDIR'+'\\'+root.split(path)[1]+'\\'+main+'.exe"'+'\n')
                            self.newFile.write('  CreateShortCut "$DESKTOP\Flow Studio.lnk" "$INSTDIR'+'\\'+root.split(path)[1]+'\\'+main+'.exe"'+'\n')
                            self.newFile.write('  SetShellVarContext current' + '\n')
                            self.newFile.write('  CreateShortCut "$INSTDIR\Flow Studio.lnk" "$INSTDIR'+'\\'+root.split(path)[1]+'\\'+main+'.exe"'+'\n')
                        else:
                            self.newFile.write('  SetShellVarContext all' + '\n')
                            self.newFile.write('  CreateDirectory "$SMPROGRAMS\FlowStudio"'+'\n')
                            self.newFile.write('  CreateShortCut "$SMPROGRAMS\FlowStudio\Flow Studio Pro.lnk" "$INSTDIR'+'\\'+root.split(path)[1]+'\\'+main+'.exe"'+'\n')
                            self.newFile.write('  CreateShortCut "$DESKTOP\Flow Studio Pro.lnk" "$INSTDIR'+'\\'+root.split(path)[1]+'\\'+main+'.exe"'+'\n')
                            self.newFile.write('  SetShellVarContext current' + '\n')
                            self.newFile.write('  CreateShortCut "$INSTDIR\Flow Studio Pro.lnk" "$INSTDIR'+'\\'+root.split(path)[1]+'\\'+main+'.exe"'+'\n')

        self.newFile.write('  WriteRegStr HKCU "Software\FlowStudio" "" $INSTDIR'+"\n")
        self.userPath = os.path.expanduser('~') + '\\flow'
        self.newFile.write('  Delete "' + self.userPath + '\open_file_path.txt"' + '\n')
        # self.newFile.write('  Delete "' + self.userPath + '\helpRecordDataForLicense.pkl"' + '\n')
        self.newFile.write('  RMDir "' + self.userPath + '"' + '\n')
        self.newFile.write('SectionEnd' + '\n\n')

    def handleSectionAfter(self):
        afterText='Section -AdditionalIcons\n' \
                  '  SetOutPath $INSTDIR\n' \
                  '  SetShellVarContext all\n' \
                  '  CreateShortCut "$SMPROGRAMS\FlowStudio\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"\n' \
                  '  SetShellVarContext current\n' \
                  'SectionEnd\n\n' \
                  'Section -Post\n' \
                  r'  writeUninstaller "$INSTDIR\uninstaller.exe"'+"\n" \
                  '  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\main\main.exe"\n' \
                  '  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayName" "${PRODUCT_NAME}"\n' \
                  '  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"\n' \
                  '  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"\n' \
                  '  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\\resources\main-theme.ico"\n' \
                  r'  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninstaller.exe"'+"\n" \
                  'SectionEnd\n'
        self.newFile.write(afterText)

    def handleSectionUninstall(self, path):
        self.newFile.write('\n')
        self.newFile.write('\n')

        self.newFile.write('Function un.onUninstSuccess' + '\n')
        self.newFile.write('  HideWindow' + '\n')
        self.newFile.write(
            '  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) has been successfully removed from your computer."' + '\n')
        self.newFile.write('FunctionEnd' + '\n')
        self.newFile.write('\n')
        self.newFile.write('Function un.onInit' + '\n')
        self.newFile.write(
            '  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Do you really want to completely remove $(^Name), and all of its components?" IDYES +2' + '\n')
        self.newFile.write('  Abort' + '\n')
        self.newFile.write('FunctionEnd' + '\n')
        self.newFile.write('\n')
        self.newFile.write('Section Uninstall' + '\n')
        self.newFile.write('  Delete "$INSTDIR\${PRODUCT_NAME}.lnk"' + '\n')
        self.newFile.write('  Delete "$INSTDIR\\uninst.exe"' + '\n')

        self.newFile.write('  DeleteRegKey HKCU "Software\FlowStudio" ' + '\n')
        rootPath = []
        for root, dirs, files in os.walk(path):
            if root == path:
                for dir in dirs:
                    rootPath.append(root + '\\' + dir)
                continue

            for file in files:
                fileRoot = os.path.join(root, file)
                writetext = '  Delete "$INSTDIR' + fileRoot[len(path):] + '"\n'
                self.newFile.write(writetext)
        self.newFile.write('\n')
        self.userPath = os.path.expanduser('~') + '\\flow'
        self.newFile.write('  Delete "' + self.userPath + '\open_file_path.txt"' + '\n')
        # self.newFile.write('  Delete "' + self.userPath + '\helpRecordDataForLicense.pkl"' + '\n')
        self.newFile.write('  RMDir "' + self.userPath + '"' + '\n')
        self.newFile.write('  SetShellVarContext all' + '\n')
        self.newFile.write('  Delete "$SMPROGRAMS\FlowStudio\\Uninstall.lnk"' + '\n')
        self.newFile.write('  Delete "$SMPROGRAMS\FlowStudio\Website.lnk"' + '\n')
        with open('constant.json', 'r') as file:
            data = json.load(file)
        tier = data.get('tier', 'free')
        if tier == 'free':
            self.newFile.write('  Delete "$DESKTOP\Flow Studio.lnk"' + '\n')
            self.newFile.write('  Delete "$SMPROGRAMS\FlowStudio\Flow Studio.lnk"' + '\n')
        else:
            self.newFile.write('  Delete "$DESKTOP\Flow Studio Pro.lnk"' + '\n')
            self.newFile.write('  Delete "$SMPROGRAMS\FlowStudio\Flow Studio Pro.lnk"' + '\n\n')

        dirPath = []
        for root, dirs, files in os.walk(path):
            for dir in dirs:
                dirRoot = os.path.join(root, dir)
                dirPath.append(dirRoot)

        dirPath.reverse()
        self.newFile.write('  RMDir "$SMPROGRAMS\FlowStudio"' + '\n')
        self.newFile.write('  SetShellVarContext current' + '\n')
        for dir in dirPath:
            self.newFile.write('  RMDir "$INSTDIR' + dir.split(path)[1] + '"\n')

        self.newFile.write('  RMDir /r "$INSTDIR"' + '\n')
        self.newFile.write('\n')
        self.newFile.write('  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"' + '\n')
        self.newFile.write('  DeleteRegKey HKLM "${PRODUCT_UNINST_KEY}"' + '\n')
        self.newFile.write('  SetAutoClose true' + '\n')

        self.newFile.write('SectionEnd')

class prepareWork():
    def __init__(self):
        # PROD_API_BASE_URL = 'https://www.tymecho.com/tomcat/flowstudio/'
        # if API_BASE_URL != PROD_API_BASE_URL:
        #     print(
        #         f'value of API_BASE_URL in flow_build_manager.py should be {PROD_API_BASE_URL} when releasing, please '
        #         f'modify.')
        #     return
        self.renewDistAndBuild()
        self.buildWithSpec()
        self.createAndCopyFolderToDist()
        self.otherOperate()
        FileFill()
        # self.removeFold()

    def renewDistAndBuild(self):
        # check dist whether in flowstudio,if True,delete it, always create a new "dist" folder.
        if os.path.exists('dist'):
            rootdir = "dist"
            filelist = os.listdir(rootdir)
            for f in filelist:
                filepath = os.path.join(rootdir, f)
                if os.path.isfile(filepath):
                    os.remove(filepath)
                elif os.path.isdir(filepath):
                    shutil.rmtree(filepath, True)
            shutil.rmtree(rootdir, True)
        os.mkdir('dist')

        # check build whether in flowstudio,if True,delete it and always create a new "build" folder.
        if os.path.exists('build'):
            rootdir = "build"
            filelist = os.listdir(rootdir)
            for f in filelist:
                filepath = os.path.join(rootdir, f)
                if os.path.isfile(filepath):
                    os.remove(filepath)
                elif os.path.isdir(filepath):
                    shutil.rmtree(filepath, True)
            shutil.rmtree(rootdir, True)
        os.mkdir('build')

    def buildWithSpec(self):
        # build we project by main.spec
        build = 'pyinstaller main.spec'
        build_process = subprocess.Popen(build, shell=True, stdout=subprocess.PIPE)
        build_process.wait()
        print("pyinstaller build process done...")

    def createAndCopyFolderToDist(self):
        # read constant.json to tier
        with open('constant.json', 'r') as file:
            data = json.load(file)
        tier = data.get('tier', 'free')  # default 'free'

        # create folder in dist
        os.mkdir(os.path.join('dist', 'bin'))
        os.mkdir(os.path.join('dist', 'bin', 'setting'))
        os.mkdir(os.path.join('dist', 'resources'))
        os.mkdir(os.path.join('dist', 'main', 'setting'))
        os.mkdir(os.path.join('dist', 'main', 'template'))
        print("create new folder")

        # copy bin folder to dist
        cp_bin = 'copy "%s" "%s"' % (os.path.join('..', 'bin'), os.path.join('dist', 'bin'))
        print('cp_bin', cp_bin)
        cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
        cp_bin_process.wait()

        # copy resources folder to dist
        cp_resources = 'copy "%s" "%s"' % (os.path.join('..', 'resources'), os.path.join('dist', 'resources'))
        cp_resources_process = subprocess.Popen(cp_resources, shell=True, stdout=subprocess.PIPE)
        cp_resources_process.wait()

        dll = ['hidapi.dll', 'hidapi.lib', 'hidapi.pdb', "btapi.dll", 'iisSoundbarLib.dll', 'iisSoundbarLib.lib']
        for i in range(len(dll)):
            cp_bin = 'copy "%s" "%s"' % (os.path.join('..', 'bin', dll[i]), os.path.join('dist', 'main'))
            cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
            cp_bin_process.wait()

        # copy flowstudio\MemoryTable.csv to main
        cp_bin = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'MemoryTable.csv'), os.path.join('dist', 'main'))
        cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
        cp_bin_process.wait()

        # copy flowstudio\Flow Studio - User Guide.pdf to main
        cp_bin = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'Flow Studio - User Guide.pdf'), os.path.join('dist', 'main'))
        cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
        cp_bin_process.wait()

        # copy flowstudio\FlowStudio - Open Architecture User Guide.pdf to main
        cp_bin = 'copy "%s" "%s"' % (
        os.path.join('..', 'flowstudio', 'FlowStudio - Open Architecture User Guide.pdf'), os.path.join('dist', 'main'))
        cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
        cp_bin_process.wait()

        # copy flowstudio\constant.json to main
        cp_bin = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'constant.json'), os.path.join('dist', 'main'))
        cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
        cp_bin_process.wait()

        # copy flowstudio\head_planes_reference.glb to main
        cp_bin = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'head_planes_reference.glb'), os.path.join('dist', 'main'))
        cp_bin_process = subprocess.Popen(cp_bin, shell=True, stdout=subprocess.PIPE)
        cp_bin_process.wait()

        # copy flowstudio\template folder to main
        cp_example = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'template'), os.path.join('dist', 'main', 'template'))
        cp_example_process = subprocess.Popen(cp_example, shell=True, stdout=subprocess.PIPE)
        cp_example_process.wait()

        # check tier to package OA_template
        if tier == 'pro':
            print("Packaging OA_template for Pro tier...")
            source = os.path.join('..', 'OA_template')
            destination = os.path.join('dist', 'OA_template')
            cp_resources = 'xcopy /E /I "%s" "%s"' % (source, destination)
            cp_resources_process = subprocess.Popen(cp_resources, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            cp_resources_process.wait()
        else:
            print("Skipping OA_template for Free tier...")

        # check tier to package S7_helper
        if tier == 'pro':
            print("Packaging S7_helper for Pro tier...")
            cp_setting = 'copy "%s" "%s"' % (os.path.join('..', 'bin', 'S7_helper'), os.path.join('dist', 'bin', 'S7_helper'))
            cp_setting_process = subprocess.Popen(cp_setting, shell=True, stdout=subprocess.PIPE)
            cp_setting_process.wait()
        else:
            print("Skipping S7_helper for Free tier...")

        # copy flowstudio\setting folder to main
        cp_setting = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'setting'), os.path.join('dist', 'main', 'setting'))
        cp_setting_process = subprocess.Popen(cp_setting, shell=True, stdout=subprocess.PIPE)
        cp_setting_process.wait()

        # copy flowstudio\setting folder to bin
        cp_setting = 'copy "%s" "%s"' % (os.path.join('..', 'flowstudio', 'setting'), os.path.join('dist', 'bin', 'setting'))
        cp_setting_process = subprocess.Popen(cp_setting, shell=True, stdout=subprocess.PIPE)
        cp_setting_process.wait()

    def otherOperate(self):
        folder_name = "FLOW_Studio_Ver_%s" % (VERSION)
        rename = "rename dist %s" % (folder_name)
        rename_process = subprocess.Popen(rename, shell=True)
        rename_process.wait()
        #
        compress = "tar cvf %s.tar %s" % (folder_name, folder_name)
        compress_process = subprocess.Popen(compress, shell=True)
        compress_process.wait()
        #
        reverse_rename = "rename %s dist" % (folder_name)
        reverse_rename_process = subprocess.Popen(reverse_rename, shell=True)
        reverse_rename_process.wait()

    # def removeFold(self):
    #     remove = "rm -r dist build"
    #     remove_process = subprocess.Popen(remove, shell=True)
    #     remove_process.wait()

# prepareWork()