[pytest]
python_files = tests.py test_*.py *_tests.py
python_paths = .

addopts =
    -s -v
    --ignore=tests/flow_node/test_gain.py
    --ignore=tests/flow_node/test_mute.py
    --ignore=tests/flow_node/test_noisegen.py
    --ignore=tests/flow_node/test_polarity.py
    --ignore=tests/flow_node/test_tonegen.py
    --ignore=tests/flow_node/test_wavplayer.py

# Specific tests can be overridden through command-line parameters, such as:
# pytest tests/test_base.py tests/flow_sub_window/test_add_audio_objects.py -k "test_add_coh_bf_ao_check_ao"